// Code generated by "stringer -type=Loglevel"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LOG_ERROR-0]
	_ = x[LOG_INFO-1]
	_ = x[LOG_DEBUG-2]
	_ = x[LOG_TRACE-3]
	_ = x[LOG_WARN-4]
	_ = x[LOG_FATAL-5]
}

const _Loglevel_name = "LOG_ERRORLOG_INFOLOG_DEBUGLOG_TRACELOG_WARNLOG_FATAL"

var _Loglevel_index = [...]uint8{0, 9, 17, 26, 35, 43, 52}

func (i Loglevel) String() string {
	if i < 0 || i >= Loglevel(len(_Loglevel_index)-1) {
		return "Loglevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Loglevel_name[_Loglevel_index[i]:_Loglevel_index[i+1]]
}
