// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: bgs/low/pb/client/api/client/v2/presence_types.proto

package v2

import (
	v21 "github.com/cjbrigato/logprox/bnet/bgs/protocol/account/v2"
	v2 "github.com/cjbrigato/logprox/bnet/bgs/protocol/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresenceQueryBehavior int32

const (
	PresenceQueryBehavior_BATTLE_NET_ACCOUNT_ONLY   PresenceQueryBehavior = 0
	PresenceQueryBehavior_INCLUDE_SAME_GAME_ACCOUNT PresenceQueryBehavior = 1
	PresenceQueryBehavior_INCLUDE_ALL_GAME_ACCOUNTS PresenceQueryBehavior = 2
)

// Enum value maps for PresenceQueryBehavior.
var (
	PresenceQueryBehavior_name = map[int32]string{
		0: "BATTLE_NET_ACCOUNT_ONLY",
		1: "INCLUDE_SAME_GAME_ACCOUNT",
		2: "INCLUDE_ALL_GAME_ACCOUNTS",
	}
	PresenceQueryBehavior_value = map[string]int32{
		"BATTLE_NET_ACCOUNT_ONLY":   0,
		"INCLUDE_SAME_GAME_ACCOUNT": 1,
		"INCLUDE_ALL_GAME_ACCOUNTS": 2,
	}
)

func (x PresenceQueryBehavior) Enum() *PresenceQueryBehavior {
	p := new(PresenceQueryBehavior)
	*p = x
	return p
}

func (x PresenceQueryBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresenceQueryBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_enumTypes[0].Descriptor()
}

func (PresenceQueryBehavior) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_api_client_v2_presence_types_proto_enumTypes[0]
}

func (x PresenceQueryBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PresenceQueryBehavior) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PresenceQueryBehavior(num)
	return nil
}

// Deprecated: Use PresenceQueryBehavior.Descriptor instead.
func (PresenceQueryBehavior) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescGZIP(), []int{0}
}

type PresenceAccountStatus int32

const (
	PresenceAccountStatus_OFFLINE PresenceAccountStatus = 0
	PresenceAccountStatus_ONLINE  PresenceAccountStatus = 1
	PresenceAccountStatus_AWAY    PresenceAccountStatus = 2
	PresenceAccountStatus_DND     PresenceAccountStatus = 3
)

// Enum value maps for PresenceAccountStatus.
var (
	PresenceAccountStatus_name = map[int32]string{
		0: "OFFLINE",
		1: "ONLINE",
		2: "AWAY",
		3: "DND",
	}
	PresenceAccountStatus_value = map[string]int32{
		"OFFLINE": 0,
		"ONLINE":  1,
		"AWAY":    2,
		"DND":     3,
	}
)

func (x PresenceAccountStatus) Enum() *PresenceAccountStatus {
	p := new(PresenceAccountStatus)
	*p = x
	return p
}

func (x PresenceAccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresenceAccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_enumTypes[1].Descriptor()
}

func (PresenceAccountStatus) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_api_client_v2_presence_types_proto_enumTypes[1]
}

func (x PresenceAccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PresenceAccountStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PresenceAccountStatus(num)
	return nil
}

// Deprecated: Use PresenceAccountStatus.Descriptor instead.
func (PresenceAccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescGZIP(), []int{1}
}

type RichPresenceKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TitleId        *uint32 `protobuf:"varint,1,opt,name=title_id,json=titleId" json:"title_id,omitempty"`
	Stream         *uint32 `protobuf:"fixed32,2,opt,name=stream" json:"stream,omitempty"`
	LocalizationId *uint32 `protobuf:"varint,3,opt,name=localization_id,json=localizationId" json:"localization_id,omitempty"`
}

func (x *RichPresenceKey) Reset() {
	*x = RichPresenceKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RichPresenceKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RichPresenceKey) ProtoMessage() {}

func (x *RichPresenceKey) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RichPresenceKey.ProtoReflect.Descriptor instead.
func (*RichPresenceKey) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescGZIP(), []int{0}
}

func (x *RichPresenceKey) GetTitleId() uint32 {
	if x != nil && x.TitleId != nil {
		return *x.TitleId
	}
	return 0
}

func (x *RichPresenceKey) GetStream() uint32 {
	if x != nil && x.Stream != nil {
		return *x.Stream
	}
	return 0
}

func (x *RichPresenceKey) GetLocalizationId() uint32 {
	if x != nil && x.LocalizationId != nil {
		return *x.LocalizationId
	}
	return 0
}

type PresenceFieldKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TitleId  *uint32 `protobuf:"varint,1,opt,name=title_id,json=titleId" json:"title_id,omitempty"`
	Group    *uint32 `protobuf:"varint,2,opt,name=group" json:"group,omitempty"`
	Field    *uint32 `protobuf:"varint,3,opt,name=field" json:"field,omitempty"`
	UniqueId *uint64 `protobuf:"varint,4,opt,name=unique_id,json=uniqueId" json:"unique_id,omitempty"`
}

func (x *PresenceFieldKey) Reset() {
	*x = PresenceFieldKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresenceFieldKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceFieldKey) ProtoMessage() {}

func (x *PresenceFieldKey) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceFieldKey.ProtoReflect.Descriptor instead.
func (*PresenceFieldKey) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescGZIP(), []int{1}
}

func (x *PresenceFieldKey) GetTitleId() uint32 {
	if x != nil && x.TitleId != nil {
		return *x.TitleId
	}
	return 0
}

func (x *PresenceFieldKey) GetGroup() uint32 {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return 0
}

func (x *PresenceFieldKey) GetField() uint32 {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return 0
}

func (x *PresenceFieldKey) GetUniqueId() uint64 {
	if x != nil && x.UniqueId != nil {
		return *x.UniqueId
	}
	return 0
}

type PresenceField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key           *PresenceFieldKey `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value         *v2.Variant       `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Deleted       *bool             `protobuf:"varint,3,opt,name=deleted" json:"deleted,omitempty"`
	UpdatedTimeUs *uint64           `protobuf:"varint,4,opt,name=updated_time_us,json=updatedTimeUs" json:"updated_time_us,omitempty"`
}

func (x *PresenceField) Reset() {
	*x = PresenceField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresenceField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceField) ProtoMessage() {}

func (x *PresenceField) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceField.ProtoReflect.Descriptor instead.
func (*PresenceField) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescGZIP(), []int{2}
}

func (x *PresenceField) GetKey() *PresenceFieldKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PresenceField) GetValue() *v2.Variant {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PresenceField) GetDeleted() bool {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return false
}

func (x *PresenceField) GetUpdatedTimeUs() uint64 {
	if x != nil && x.UpdatedTimeUs != nil {
		return *x.UpdatedTimeUs
	}
	return 0
}

type PresenceFieldState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId    *uint64                `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	GameAccount  *v21.GameAccountHandle `protobuf:"bytes,2,opt,name=game_account,json=gameAccount" json:"game_account,omitempty"`
	Fields       []*PresenceField       `protobuf:"bytes,3,rep,name=fields" json:"fields,omitempty"`
	OldestTimeUs *uint64                `protobuf:"varint,4,opt,name=oldest_time_us,json=oldestTimeUs" json:"oldest_time_us,omitempty"`
}

func (x *PresenceFieldState) Reset() {
	*x = PresenceFieldState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresenceFieldState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceFieldState) ProtoMessage() {}

func (x *PresenceFieldState) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceFieldState.ProtoReflect.Descriptor instead.
func (*PresenceFieldState) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescGZIP(), []int{3}
}

func (x *PresenceFieldState) GetAccountId() uint64 {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return 0
}

func (x *PresenceFieldState) GetGameAccount() *v21.GameAccountHandle {
	if x != nil {
		return x.GameAccount
	}
	return nil
}

func (x *PresenceFieldState) GetFields() []*PresenceField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *PresenceFieldState) GetOldestTimeUs() uint64 {
	if x != nil && x.OldestTimeUs != nil {
		return *x.OldestTimeUs
	}
	return 0
}

type PresenceFieldUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    *PresenceFieldKey `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value  *v2.Variant       `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Delete *bool             `protobuf:"varint,3,opt,name=delete" json:"delete,omitempty"`
}

func (x *PresenceFieldUpdate) Reset() {
	*x = PresenceFieldUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresenceFieldUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceFieldUpdate) ProtoMessage() {}

func (x *PresenceFieldUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceFieldUpdate.ProtoReflect.Descriptor instead.
func (*PresenceFieldUpdate) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescGZIP(), []int{4}
}

func (x *PresenceFieldUpdate) GetKey() *PresenceFieldKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PresenceFieldUpdate) GetValue() *v2.Variant {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PresenceFieldUpdate) GetDelete() bool {
	if x != nil && x.Delete != nil {
		return *x.Delete
	}
	return false
}

type PresenceOnlineGameAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameAccount  *v21.GameAccountHandle `protobuf:"bytes,1,opt,name=game_account,json=gameAccount" json:"game_account,omitempty"`
	OnlineTimeUs *uint64                `protobuf:"varint,2,opt,name=online_time_us,json=onlineTimeUs" json:"online_time_us,omitempty"`
}

func (x *PresenceOnlineGameAccount) Reset() {
	*x = PresenceOnlineGameAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresenceOnlineGameAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceOnlineGameAccount) ProtoMessage() {}

func (x *PresenceOnlineGameAccount) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceOnlineGameAccount.ProtoReflect.Descriptor instead.
func (*PresenceOnlineGameAccount) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescGZIP(), []int{5}
}

func (x *PresenceOnlineGameAccount) GetGameAccount() *v21.GameAccountHandle {
	if x != nil {
		return x.GameAccount
	}
	return nil
}

func (x *PresenceOnlineGameAccount) GetOnlineTimeUs() uint64 {
	if x != nil && x.OnlineTimeUs != nil {
		return *x.OnlineTimeUs
	}
	return 0
}

type PresenceOnlineGameAccountFieldValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OnlineGameAccounts []*PresenceOnlineGameAccount `protobuf:"bytes,1,rep,name=online_game_accounts,json=onlineGameAccounts" json:"online_game_accounts,omitempty"`
}

func (x *PresenceOnlineGameAccountFieldValue) Reset() {
	*x = PresenceOnlineGameAccountFieldValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresenceOnlineGameAccountFieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceOnlineGameAccountFieldValue) ProtoMessage() {}

func (x *PresenceOnlineGameAccountFieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceOnlineGameAccountFieldValue.ProtoReflect.Descriptor instead.
func (*PresenceOnlineGameAccountFieldValue) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescGZIP(), []int{6}
}

func (x *PresenceOnlineGameAccountFieldValue) GetOnlineGameAccounts() []*PresenceOnlineGameAccount {
	if x != nil {
		return x.OnlineGameAccounts
	}
	return nil
}

type PresenceExternalIdentityFieldValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueId  *string `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId" json:"unique_id,omitempty"`
	DisplayId *string `protobuf:"bytes,2,opt,name=display_id,json=displayId" json:"display_id,omitempty"`
}

func (x *PresenceExternalIdentityFieldValue) Reset() {
	*x = PresenceExternalIdentityFieldValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresenceExternalIdentityFieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceExternalIdentityFieldValue) ProtoMessage() {}

func (x *PresenceExternalIdentityFieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceExternalIdentityFieldValue.ProtoReflect.Descriptor instead.
func (*PresenceExternalIdentityFieldValue) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescGZIP(), []int{7}
}

func (x *PresenceExternalIdentityFieldValue) GetUniqueId() string {
	if x != nil && x.UniqueId != nil {
		return *x.UniqueId
	}
	return ""
}

func (x *PresenceExternalIdentityFieldValue) GetDisplayId() string {
	if x != nil && x.DisplayId != nil {
		return *x.DisplayId
	}
	return ""
}

var File_bgs_low_pb_client_api_client_v2_presence_types_proto protoreflect.FileDescriptor

var file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDesc = []byte{
	0x0a, 0x34, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x76,
	0x32, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x32,
	0x1a, 0x39, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x76,
	0x32, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x35, 0x62, 0x67, 0x73,
	0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x0f, 0x52, 0x69, 0x63, 0x68, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x63, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07,
	0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x22, 0x76, 0x0a, 0x10, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x22, 0xbf, 0x01, 0x0a, 0x0d, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x3c, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65,
	0x2e, 0x76, 0x32, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x22, 0xe9, 0x01, 0x0a, 0x12,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x4d, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76,
	0x32, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x3f, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x12, 0x24, 0x0a, 0x0e, 0x6f, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6f, 0x6c, 0x64, 0x65, 0x73,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x22, 0x9b, 0x01, 0x0a, 0x13, 0x50, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x3c, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x62,
	0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2e, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62,
	0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x19, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x63, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x4d, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x62, 0x67, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x76, 0x32, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x23, 0x50, 0x72, 0x65,
	0x73, 0x65, 0x6e, 0x63, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x65, 0x0a, 0x14, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33,
	0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x63, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x12, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x22, 0x60, 0x0a, 0x22, 0x50, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x63, 0x65, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x2a, 0x72, 0x0a, 0x15, 0x50, 0x72, 0x65,
	0x73, 0x65, 0x6e, 0x63, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69,
	0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x17, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45, 0x5f, 0x4e, 0x45, 0x54,
	0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x10, 0x00, 0x12,
	0x1d, 0x0a, 0x19, 0x49, 0x4e, 0x43, 0x4c, 0x55, 0x44, 0x45, 0x5f, 0x53, 0x41, 0x4d, 0x45, 0x5f,
	0x47, 0x41, 0x4d, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x1d,
	0x0a, 0x19, 0x49, 0x4e, 0x43, 0x4c, 0x55, 0x44, 0x45, 0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x47, 0x41,
	0x4d, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x53, 0x10, 0x02, 0x2a, 0x43, 0x0a,
	0x15, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x41, 0x57, 0x41, 0x59, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x4e, 0x44,
	0x10, 0x03, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x6a, 0x62, 0x72, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x70, 0x72,
	0x6f, 0x78, 0x2f, 0x62, 0x6e, 0x65, 0x74, 0x2f, 0x62, 0x67, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x76, 0x32,
}

var (
	file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescOnce sync.Once
	file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescData = file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDesc
)

func file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescGZIP() []byte {
	file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescOnce.Do(func() {
		file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescData)
	})
	return file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDescData
}

var file_bgs_low_pb_client_api_client_v2_presence_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bgs_low_pb_client_api_client_v2_presence_types_proto_goTypes = []interface{}{
	(PresenceQueryBehavior)(0),                  // 0: bgs.protocol.presence.v2.PresenceQueryBehavior
	(PresenceAccountStatus)(0),                  // 1: bgs.protocol.presence.v2.PresenceAccountStatus
	(*RichPresenceKey)(nil),                     // 2: bgs.protocol.presence.v2.RichPresenceKey
	(*PresenceFieldKey)(nil),                    // 3: bgs.protocol.presence.v2.PresenceFieldKey
	(*PresenceField)(nil),                       // 4: bgs.protocol.presence.v2.PresenceField
	(*PresenceFieldState)(nil),                  // 5: bgs.protocol.presence.v2.PresenceFieldState
	(*PresenceFieldUpdate)(nil),                 // 6: bgs.protocol.presence.v2.PresenceFieldUpdate
	(*PresenceOnlineGameAccount)(nil),           // 7: bgs.protocol.presence.v2.PresenceOnlineGameAccount
	(*PresenceOnlineGameAccountFieldValue)(nil), // 8: bgs.protocol.presence.v2.PresenceOnlineGameAccountFieldValue
	(*PresenceExternalIdentityFieldValue)(nil),  // 9: bgs.protocol.presence.v2.PresenceExternalIdentityFieldValue
	(*v2.Variant)(nil),                          // 10: bgs.protocol.v2.Variant
	(*v21.GameAccountHandle)(nil),               // 11: bgs.protocol.account.v2.GameAccountHandle
}
var file_bgs_low_pb_client_api_client_v2_presence_types_proto_depIdxs = []int32{
	3,  // 0: bgs.protocol.presence.v2.PresenceField.key:type_name -> bgs.protocol.presence.v2.PresenceFieldKey
	10, // 1: bgs.protocol.presence.v2.PresenceField.value:type_name -> bgs.protocol.v2.Variant
	11, // 2: bgs.protocol.presence.v2.PresenceFieldState.game_account:type_name -> bgs.protocol.account.v2.GameAccountHandle
	4,  // 3: bgs.protocol.presence.v2.PresenceFieldState.fields:type_name -> bgs.protocol.presence.v2.PresenceField
	3,  // 4: bgs.protocol.presence.v2.PresenceFieldUpdate.key:type_name -> bgs.protocol.presence.v2.PresenceFieldKey
	10, // 5: bgs.protocol.presence.v2.PresenceFieldUpdate.value:type_name -> bgs.protocol.v2.Variant
	11, // 6: bgs.protocol.presence.v2.PresenceOnlineGameAccount.game_account:type_name -> bgs.protocol.account.v2.GameAccountHandle
	7,  // 7: bgs.protocol.presence.v2.PresenceOnlineGameAccountFieldValue.online_game_accounts:type_name -> bgs.protocol.presence.v2.PresenceOnlineGameAccount
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_bgs_low_pb_client_api_client_v2_presence_types_proto_init() }
func file_bgs_low_pb_client_api_client_v2_presence_types_proto_init() {
	if File_bgs_low_pb_client_api_client_v2_presence_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RichPresenceKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresenceFieldKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresenceField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresenceFieldState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresenceFieldUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresenceOnlineGameAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresenceOnlineGameAccountFieldValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresenceExternalIdentityFieldValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bgs_low_pb_client_api_client_v2_presence_types_proto_goTypes,
		DependencyIndexes: file_bgs_low_pb_client_api_client_v2_presence_types_proto_depIdxs,
		EnumInfos:         file_bgs_low_pb_client_api_client_v2_presence_types_proto_enumTypes,
		MessageInfos:      file_bgs_low_pb_client_api_client_v2_presence_types_proto_msgTypes,
	}.Build()
	File_bgs_low_pb_client_api_client_v2_presence_types_proto = out.File
	file_bgs_low_pb_client_api_client_v2_presence_types_proto_rawDesc = nil
	file_bgs_low_pb_client_api_client_v2_presence_types_proto_goTypes = nil
	file_bgs_low_pb_client_api_client_v2_presence_types_proto_depIdxs = nil
}
