// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: ClientMessage.proto

package ClientMessage

import (
	Online "github.com/cjbrigato/d4-bnet-mitm/bnet/Fenris/Online"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindUserProxyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectInfo *Online.ConnectionInfo `protobuf:"bytes,1,opt,name=connect_info,json=connectInfo" json:"connect_info,omitempty"`
	ErrorCode   *uint32                `protobuf:"varint,2,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	Token       *uint64                `protobuf:"varint,3,opt,name=token" json:"token,omitempty"`
	EntryKey    *Online.QueueEntryKey  `protobuf:"bytes,4,opt,name=entry_key,json=entryKey" json:"entry_key,omitempty"`
	Trace       *Online.Trace          `protobuf:"bytes,5,opt,name=trace" json:"trace,omitempty"`
}

func (x *FindUserProxyResponse) Reset() {
	*x = FindUserProxyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserProxyResponse) ProtoMessage() {}

func (x *FindUserProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserProxyResponse.ProtoReflect.Descriptor instead.
func (*FindUserProxyResponse) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{0}
}

func (x *FindUserProxyResponse) GetConnectInfo() *Online.ConnectionInfo {
	if x != nil {
		return x.ConnectInfo
	}
	return nil
}

func (x *FindUserProxyResponse) GetErrorCode() uint32 {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return 0
}

func (x *FindUserProxyResponse) GetToken() uint64 {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return 0
}

func (x *FindUserProxyResponse) GetEntryKey() *Online.QueueEntryKey {
	if x != nil {
		return x.EntryKey
	}
	return nil
}

func (x *FindUserProxyResponse) GetTrace() *Online.Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

type PingConnectInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId           *uint64 `protobuf:"varint,1,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	ExpectedResultCount *uint32 `protobuf:"varint,2,opt,name=expected_result_count,json=expectedResultCount" json:"expected_result_count,omitempty"`
}

func (x *PingConnectInfoResponse) Reset() {
	*x = PingConnectInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingConnectInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingConnectInfoResponse) ProtoMessage() {}

func (x *PingConnectInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingConnectInfoResponse.ProtoReflect.Descriptor instead.
func (*PingConnectInfoResponse) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{1}
}

func (x *PingConnectInfoResponse) GetRequestId() uint64 {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return 0
}

func (x *PingConnectInfoResponse) GetExpectedResultCount() uint32 {
	if x != nil && x.ExpectedResultCount != nil {
		return *x.ExpectedResultCount
	}
	return 0
}

type PingConnectInfoSingleResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId       *uint64                    `protobuf:"varint,1,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	PingConnectInfo *Online.PingConnectionInfo `protobuf:"bytes,2,opt,name=ping_connect_info,json=pingConnectInfo" json:"ping_connect_info,omitempty"`
	Trace           *Online.Trace              `protobuf:"bytes,3,opt,name=trace" json:"trace,omitempty"`
}

func (x *PingConnectInfoSingleResult) Reset() {
	*x = PingConnectInfoSingleResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingConnectInfoSingleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingConnectInfoSingleResult) ProtoMessage() {}

func (x *PingConnectInfoSingleResult) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingConnectInfoSingleResult.ProtoReflect.Descriptor instead.
func (*PingConnectInfoSingleResult) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{2}
}

func (x *PingConnectInfoSingleResult) GetRequestId() uint64 {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return 0
}

func (x *PingConnectInfoSingleResult) GetPingConnectInfo() *Online.PingConnectionInfo {
	if x != nil {
		return x.PingConnectInfo
	}
	return nil
}

func (x *PingConnectInfoSingleResult) GetTrace() *Online.Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

type QueueEntryAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntryKey       *Online.QueueEntryKey `protobuf:"bytes,1,opt,name=entry_key,json=entryKey" json:"entry_key,omitempty"`
	AvgWaitSeconds *uint32               `protobuf:"varint,2,opt,name=avg_wait_seconds,json=avgWaitSeconds" json:"avg_wait_seconds,omitempty"`
}

func (x *QueueEntryAdded) Reset() {
	*x = QueueEntryAdded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueEntryAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueEntryAdded) ProtoMessage() {}

func (x *QueueEntryAdded) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueEntryAdded.ProtoReflect.Descriptor instead.
func (*QueueEntryAdded) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{3}
}

func (x *QueueEntryAdded) GetEntryKey() *Online.QueueEntryKey {
	if x != nil {
		return x.EntryKey
	}
	return nil
}

func (x *QueueEntryAdded) GetAvgWaitSeconds() uint32 {
	if x != nil && x.AvgWaitSeconds != nil {
		return *x.AvgWaitSeconds
	}
	return 0
}

type QueueUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntryKey       *Online.QueueEntryKey `protobuf:"bytes,1,opt,name=entry_key,json=entryKey" json:"entry_key,omitempty"`
	AvgWaitSeconds *uint32               `protobuf:"varint,2,opt,name=avg_wait_seconds,json=avgWaitSeconds" json:"avg_wait_seconds,omitempty"`
}

func (x *QueueUpdate) Reset() {
	*x = QueueUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueUpdate) ProtoMessage() {}

func (x *QueueUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_ClientMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueUpdate.ProtoReflect.Descriptor instead.
func (*QueueUpdate) Descriptor() ([]byte, []int) {
	return file_ClientMessage_proto_rawDescGZIP(), []int{4}
}

func (x *QueueUpdate) GetEntryKey() *Online.QueueEntryKey {
	if x != nil {
		return x.EntryKey
	}
	return nil
}

func (x *QueueUpdate) GetAvgWaitSeconds() uint32 {
	if x != nil && x.AvgWaitSeconds != nil {
		return *x.AvgWaitSeconds
	}
	return 0
}

var File_ClientMessage_proto protoreflect.FileDescriptor

var file_ClientMessage_proto_rawDesc = []byte{
	0x0a, 0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x46, 0x65, 0x6e, 0x72, 0x69, 0x73, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf5, 0x01,
	0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x46, 0x65, 0x6e, 0x72, 0x69, 0x73, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x39,
	0x0a, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x46, 0x65, 0x6e, 0x72, 0x69, 0x73, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x52,
	0x08, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x46, 0x65, 0x6e, 0x72, 0x69,
	0x73, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x52, 0x05,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x22, 0x6c, 0x0a, 0x17, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x32, 0x0a, 0x15, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13,
	0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0xb7, 0x01, 0x0a, 0x1b, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x4d, 0x0a, 0x11, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x46, 0x65, 0x6e, 0x72, 0x69, 0x73, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0f, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x2a, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x46, 0x65, 0x6e, 0x72, 0x69, 0x73, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x22, 0x76, 0x0a,
	0x0f, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x41, 0x64, 0x64, 0x65, 0x64,
	0x12, 0x39, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x46, 0x65, 0x6e, 0x72, 0x69, 0x73, 0x2e, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4b, 0x65,
	0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x10, 0x61,
	0x76, 0x67, 0x5f, 0x77, 0x61, 0x69, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x61, 0x76, 0x67, 0x57, 0x61, 0x69, 0x74, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x72, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x46, 0x65, 0x6e, 0x72, 0x69, 0x73,
	0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x12,
	0x28, 0x0a, 0x10, 0x61, 0x76, 0x67, 0x5f, 0x77, 0x61, 0x69, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x61, 0x76, 0x67, 0x57, 0x61,
	0x69, 0x74, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6a, 0x62, 0x72, 0x69, 0x67, 0x61, 0x74,
	0x6f, 0x2f, 0x64, 0x34, 0x2d, 0x62, 0x6e, 0x65, 0x74, 0x2d, 0x6d, 0x69, 0x74, 0x6d, 0x2f, 0x62,
	0x6e, 0x65, 0x74, 0x2f, 0x46, 0x65, 0x6e, 0x72, 0x69, 0x73, 0x2f, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
}

var (
	file_ClientMessage_proto_rawDescOnce sync.Once
	file_ClientMessage_proto_rawDescData = file_ClientMessage_proto_rawDesc
)

func file_ClientMessage_proto_rawDescGZIP() []byte {
	file_ClientMessage_proto_rawDescOnce.Do(func() {
		file_ClientMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_ClientMessage_proto_rawDescData)
	})
	return file_ClientMessage_proto_rawDescData
}

var file_ClientMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ClientMessage_proto_goTypes = []interface{}{
	(*FindUserProxyResponse)(nil),       // 0: Fenris.ClientMessage.FindUserProxyResponse
	(*PingConnectInfoResponse)(nil),     // 1: Fenris.ClientMessage.PingConnectInfoResponse
	(*PingConnectInfoSingleResult)(nil), // 2: Fenris.ClientMessage.PingConnectInfoSingleResult
	(*QueueEntryAdded)(nil),             // 3: Fenris.ClientMessage.QueueEntryAdded
	(*QueueUpdate)(nil),                 // 4: Fenris.ClientMessage.QueueUpdate
	(*Online.ConnectionInfo)(nil),       // 5: Fenris.Online.ConnectionInfo
	(*Online.QueueEntryKey)(nil),        // 6: Fenris.Online.QueueEntryKey
	(*Online.Trace)(nil),                // 7: Fenris.Online.Trace
	(*Online.PingConnectionInfo)(nil),   // 8: Fenris.Online.PingConnectionInfo
}
var file_ClientMessage_proto_depIdxs = []int32{
	5, // 0: Fenris.ClientMessage.FindUserProxyResponse.connect_info:type_name -> Fenris.Online.ConnectionInfo
	6, // 1: Fenris.ClientMessage.FindUserProxyResponse.entry_key:type_name -> Fenris.Online.QueueEntryKey
	7, // 2: Fenris.ClientMessage.FindUserProxyResponse.trace:type_name -> Fenris.Online.Trace
	8, // 3: Fenris.ClientMessage.PingConnectInfoSingleResult.ping_connect_info:type_name -> Fenris.Online.PingConnectionInfo
	7, // 4: Fenris.ClientMessage.PingConnectInfoSingleResult.trace:type_name -> Fenris.Online.Trace
	6, // 5: Fenris.ClientMessage.QueueEntryAdded.entry_key:type_name -> Fenris.Online.QueueEntryKey
	6, // 6: Fenris.ClientMessage.QueueUpdate.entry_key:type_name -> Fenris.Online.QueueEntryKey
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_ClientMessage_proto_init() }
func file_ClientMessage_proto_init() {
	if File_ClientMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ClientMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserProxyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingConnectInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingConnectInfoSingleResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueEntryAdded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ClientMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ClientMessage_proto_goTypes,
		DependencyIndexes: file_ClientMessage_proto_depIdxs,
		MessageInfos:      file_ClientMessage_proto_msgTypes,
	}.Build()
	File_ClientMessage_proto = out.File
	file_ClientMessage_proto_rawDesc = nil
	file_ClientMessage_proto_goTypes = nil
	file_ClientMessage_proto_depIdxs = nil
}
