// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: bgs/low/pb/client/club_membership_types.proto

package v1

import (
	protocol "github.com/cjbrigato/logprox/bnet/bgs/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClubMembershipFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId *MemberId       `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	Type     *UniqueClubType `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (x *ClubMembershipFilter) Reset() {
	*x = ClubMembershipFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClubMembershipFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClubMembershipFilter) ProtoMessage() {}

func (x *ClubMembershipFilter) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClubMembershipFilter.ProtoReflect.Descriptor instead.
func (*ClubMembershipFilter) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_membership_types_proto_rawDescGZIP(), []int{0}
}

func (x *ClubMembershipFilter) GetMemberId() *MemberId {
	if x != nil {
		return x.MemberId
	}
	return nil
}

func (x *ClubMembershipFilter) GetType() *UniqueClubType {
	if x != nil {
		return x.Type
	}
	return nil
}

type ClubMembershipSubscribeOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter []*ClubMembershipFilter `protobuf:"bytes,1,rep,name=filter" json:"filter,omitempty"`
}

func (x *ClubMembershipSubscribeOptions) Reset() {
	*x = ClubMembershipSubscribeOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClubMembershipSubscribeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClubMembershipSubscribeOptions) ProtoMessage() {}

func (x *ClubMembershipSubscribeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClubMembershipSubscribeOptions.ProtoReflect.Descriptor instead.
func (*ClubMembershipSubscribeOptions) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_membership_types_proto_rawDescGZIP(), []int{1}
}

func (x *ClubMembershipSubscribeOptions) GetFilter() []*ClubMembershipFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ClubMembershipGetStateOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter []*ClubMembershipFilter `protobuf:"bytes,1,rep,name=filter" json:"filter,omitempty"`
}

func (x *ClubMembershipGetStateOptions) Reset() {
	*x = ClubMembershipGetStateOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClubMembershipGetStateOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClubMembershipGetStateOptions) ProtoMessage() {}

func (x *ClubMembershipGetStateOptions) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClubMembershipGetStateOptions.ProtoReflect.Descriptor instead.
func (*ClubMembershipGetStateOptions) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_membership_types_proto_rawDescGZIP(), []int{2}
}

func (x *ClubMembershipGetStateOptions) GetFilter() []*ClubMembershipFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ClubMembershipDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId *MemberId        `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	Club     *ClubDescription `protobuf:"bytes,2,opt,name=club" json:"club,omitempty"`
}

func (x *ClubMembershipDescription) Reset() {
	*x = ClubMembershipDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClubMembershipDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClubMembershipDescription) ProtoMessage() {}

func (x *ClubMembershipDescription) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClubMembershipDescription.ProtoReflect.Descriptor instead.
func (*ClubMembershipDescription) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_membership_types_proto_rawDescGZIP(), []int{3}
}

func (x *ClubMembershipDescription) GetMemberId() *MemberId {
	if x != nil {
		return x.MemberId
	}
	return nil
}

func (x *ClubMembershipDescription) GetClub() *ClubDescription {
	if x != nil {
		return x.Club
	}
	return nil
}

type ClubMembershipState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description []*ClubMembershipDescription `protobuf:"bytes,1,rep,name=description" json:"description,omitempty"`
	Invitation  []*ClubInvitation            `protobuf:"bytes,2,rep,name=invitation" json:"invitation,omitempty"`
	Setting     *ClubSharedSettings          `protobuf:"bytes,3,opt,name=setting" json:"setting,omitempty"`
	MentionView *protocol.ViewMarker         `protobuf:"bytes,4,opt,name=mention_view,json=mentionView" json:"mention_view,omitempty"`
}

func (x *ClubMembershipState) Reset() {
	*x = ClubMembershipState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClubMembershipState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClubMembershipState) ProtoMessage() {}

func (x *ClubMembershipState) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClubMembershipState.ProtoReflect.Descriptor instead.
func (*ClubMembershipState) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_membership_types_proto_rawDescGZIP(), []int{4}
}

func (x *ClubMembershipState) GetDescription() []*ClubMembershipDescription {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *ClubMembershipState) GetInvitation() []*ClubInvitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

func (x *ClubMembershipState) GetSetting() *ClubSharedSettings {
	if x != nil {
		return x.Setting
	}
	return nil
}

func (x *ClubMembershipState) GetMentionView() *protocol.ViewMarker {
	if x != nil {
		return x.MentionView
	}
	return nil
}

type ClubPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClubId []uint64 `protobuf:"varint,1,rep,name=club_id,json=clubId" json:"club_id,omitempty"`
}

func (x *ClubPosition) Reset() {
	*x = ClubPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClubPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClubPosition) ProtoMessage() {}

func (x *ClubPosition) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClubPosition.ProtoReflect.Descriptor instead.
func (*ClubPosition) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_membership_types_proto_rawDescGZIP(), []int{5}
}

func (x *ClubPosition) GetClubId() []uint64 {
	if x != nil {
		return x.ClubId
	}
	return nil
}

type ClubSharedSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClubPosition *ClubPosition `protobuf:"bytes,1,opt,name=club_position,json=clubPosition" json:"club_position,omitempty"`
}

func (x *ClubSharedSettings) Reset() {
	*x = ClubSharedSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClubSharedSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClubSharedSettings) ProtoMessage() {}

func (x *ClubSharedSettings) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClubSharedSettings.ProtoReflect.Descriptor instead.
func (*ClubSharedSettings) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_membership_types_proto_rawDescGZIP(), []int{6}
}

func (x *ClubSharedSettings) GetClubPosition() *ClubPosition {
	if x != nil {
		return x.ClubPosition
	}
	return nil
}

type ClubSharedSettingsOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClubPosition *ClubPosition `protobuf:"bytes,1,opt,name=club_position,json=clubPosition" json:"club_position,omitempty"`
}

func (x *ClubSharedSettingsOptions) Reset() {
	*x = ClubSharedSettingsOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClubSharedSettingsOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClubSharedSettingsOptions) ProtoMessage() {}

func (x *ClubSharedSettingsOptions) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClubSharedSettingsOptions.ProtoReflect.Descriptor instead.
func (*ClubSharedSettingsOptions) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_membership_types_proto_rawDescGZIP(), []int{7}
}

func (x *ClubSharedSettingsOptions) GetClubPosition() *ClubPosition {
	if x != nil {
		return x.ClubPosition
	}
	return nil
}

type ClubSharedSettingsAssignment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClubPosition *ClubPosition `protobuf:"bytes,1,opt,name=club_position,json=clubPosition" json:"club_position,omitempty"`
}

func (x *ClubSharedSettingsAssignment) Reset() {
	*x = ClubSharedSettingsAssignment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClubSharedSettingsAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClubSharedSettingsAssignment) ProtoMessage() {}

func (x *ClubSharedSettingsAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_club_membership_types_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClubSharedSettingsAssignment.ProtoReflect.Descriptor instead.
func (*ClubSharedSettingsAssignment) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_membership_types_proto_rawDescGZIP(), []int{8}
}

func (x *ClubSharedSettingsAssignment) GetClubPosition() *ClubPosition {
	if x != nil {
		return x.ClubPosition
	}
	return nil
}

var File_bgs_low_pb_client_club_membership_types_proto protoreflect.FileDescriptor

var file_bgs_low_pb_client_club_membership_types_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6c, 0x75, 0x62, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x14, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c,
	0x75, 0x62, 0x2e, 0x76, 0x31, 0x1a, 0x21, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70,
	0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6c, 0x75, 0x62, 0x5f, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f,
	0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6c, 0x75, 0x62,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x26, 0x62, 0x67, 0x73,
	0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63,
	0x6c, 0x75, 0x62, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6c, 0x75, 0x62, 0x5f, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x27, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f,
	0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6c, 0x75, 0x62,
	0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x28, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x62, 0x67, 0x73,
	0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x72,
	0x70, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d,
	0x01, 0x0a, 0x14, 0x43, 0x6c, 0x75, 0x62, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x67, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x43, 0x6c, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x64,
	0x0a, 0x1e, 0x43, 0x6c, 0x75, 0x62, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x42, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2a, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x63, 0x6c, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x22, 0x63, 0x0a, 0x1d, 0x43, 0x6c, 0x75, 0x62, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x42, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75,
	0x62, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x93, 0x01, 0x0a, 0x19, 0x43, 0x6c,
	0x75, 0x62, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x67, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x04, 0x63, 0x6c, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x6c, 0x75, 0x62, 0x22,
	0xaf, 0x02, 0x0a, 0x13, 0x43, 0x6c, 0x75, 0x62, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x51, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x62,
	0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x44, 0x0a, 0x0a, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c,
	0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x42, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x07, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x3b, 0x0a, 0x0c, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x76, 0x69, 0x65, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x67, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x72, 0x52, 0x0b, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x65,
	0x77, 0x22, 0x27, 0x0a, 0x0c, 0x43, 0x6c, 0x75, 0x62, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x04, 0x52, 0x06, 0x63, 0x6c, 0x75, 0x62, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x12, 0x43, 0x6c,
	0x75, 0x62, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x12, 0x47, 0x0a, 0x0d, 0x63, 0x6c, 0x75, 0x62, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6c, 0x75, 0x62, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x63, 0x6c, 0x75,
	0x62, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x64, 0x0a, 0x19, 0x43, 0x6c, 0x75,
	0x62, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x47, 0x0a, 0x0d, 0x63, 0x6c, 0x75, 0x62, 0x5f, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x75,
	0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0c, 0x63, 0x6c, 0x75, 0x62, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x67, 0x0a, 0x1c, 0x43, 0x6c, 0x75, 0x62, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x47, 0x0a, 0x0d, 0x63, 0x6c, 0x75, 0x62, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c,
	0x75, 0x62, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x63, 0x6c, 0x75, 0x62,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6a, 0x62, 0x72, 0x69, 0x67, 0x61, 0x74, 0x6f,
	0x2f, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x78, 0x2f, 0x62, 0x6e, 0x65, 0x74, 0x2f, 0x62, 0x67,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6c, 0x75, 0x62, 0x2f,
	0x76, 0x31,
}

var (
	file_bgs_low_pb_client_club_membership_types_proto_rawDescOnce sync.Once
	file_bgs_low_pb_client_club_membership_types_proto_rawDescData = file_bgs_low_pb_client_club_membership_types_proto_rawDesc
)

func file_bgs_low_pb_client_club_membership_types_proto_rawDescGZIP() []byte {
	file_bgs_low_pb_client_club_membership_types_proto_rawDescOnce.Do(func() {
		file_bgs_low_pb_client_club_membership_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_bgs_low_pb_client_club_membership_types_proto_rawDescData)
	})
	return file_bgs_low_pb_client_club_membership_types_proto_rawDescData
}

var file_bgs_low_pb_client_club_membership_types_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bgs_low_pb_client_club_membership_types_proto_goTypes = []interface{}{
	(*ClubMembershipFilter)(nil),           // 0: bgs.protocol.club.v1.ClubMembershipFilter
	(*ClubMembershipSubscribeOptions)(nil), // 1: bgs.protocol.club.v1.ClubMembershipSubscribeOptions
	(*ClubMembershipGetStateOptions)(nil),  // 2: bgs.protocol.club.v1.ClubMembershipGetStateOptions
	(*ClubMembershipDescription)(nil),      // 3: bgs.protocol.club.v1.ClubMembershipDescription
	(*ClubMembershipState)(nil),            // 4: bgs.protocol.club.v1.ClubMembershipState
	(*ClubPosition)(nil),                   // 5: bgs.protocol.club.v1.ClubPosition
	(*ClubSharedSettings)(nil),             // 6: bgs.protocol.club.v1.ClubSharedSettings
	(*ClubSharedSettingsOptions)(nil),      // 7: bgs.protocol.club.v1.ClubSharedSettingsOptions
	(*ClubSharedSettingsAssignment)(nil),   // 8: bgs.protocol.club.v1.ClubSharedSettingsAssignment
	(*MemberId)(nil),                       // 9: bgs.protocol.club.v1.MemberId
	(*UniqueClubType)(nil),                 // 10: bgs.protocol.club.v1.UniqueClubType
	(*ClubDescription)(nil),                // 11: bgs.protocol.club.v1.ClubDescription
	(*ClubInvitation)(nil),                 // 12: bgs.protocol.club.v1.ClubInvitation
	(*protocol.ViewMarker)(nil),            // 13: bgs.protocol.ViewMarker
}
var file_bgs_low_pb_client_club_membership_types_proto_depIdxs = []int32{
	9,  // 0: bgs.protocol.club.v1.ClubMembershipFilter.member_id:type_name -> bgs.protocol.club.v1.MemberId
	10, // 1: bgs.protocol.club.v1.ClubMembershipFilter.type:type_name -> bgs.protocol.club.v1.UniqueClubType
	0,  // 2: bgs.protocol.club.v1.ClubMembershipSubscribeOptions.filter:type_name -> bgs.protocol.club.v1.ClubMembershipFilter
	0,  // 3: bgs.protocol.club.v1.ClubMembershipGetStateOptions.filter:type_name -> bgs.protocol.club.v1.ClubMembershipFilter
	9,  // 4: bgs.protocol.club.v1.ClubMembershipDescription.member_id:type_name -> bgs.protocol.club.v1.MemberId
	11, // 5: bgs.protocol.club.v1.ClubMembershipDescription.club:type_name -> bgs.protocol.club.v1.ClubDescription
	3,  // 6: bgs.protocol.club.v1.ClubMembershipState.description:type_name -> bgs.protocol.club.v1.ClubMembershipDescription
	12, // 7: bgs.protocol.club.v1.ClubMembershipState.invitation:type_name -> bgs.protocol.club.v1.ClubInvitation
	6,  // 8: bgs.protocol.club.v1.ClubMembershipState.setting:type_name -> bgs.protocol.club.v1.ClubSharedSettings
	13, // 9: bgs.protocol.club.v1.ClubMembershipState.mention_view:type_name -> bgs.protocol.ViewMarker
	5,  // 10: bgs.protocol.club.v1.ClubSharedSettings.club_position:type_name -> bgs.protocol.club.v1.ClubPosition
	5,  // 11: bgs.protocol.club.v1.ClubSharedSettingsOptions.club_position:type_name -> bgs.protocol.club.v1.ClubPosition
	5,  // 12: bgs.protocol.club.v1.ClubSharedSettingsAssignment.club_position:type_name -> bgs.protocol.club.v1.ClubPosition
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_bgs_low_pb_client_club_membership_types_proto_init() }
func file_bgs_low_pb_client_club_membership_types_proto_init() {
	if File_bgs_low_pb_client_club_membership_types_proto != nil {
		return
	}
	file_bgs_low_pb_client_club_core_proto_init()
	file_bgs_low_pb_client_club_type_proto_init()
	file_bgs_low_pb_client_club_member_id_proto_init()
	file_bgs_low_pb_client_club_member_proto_init()
	file_bgs_low_pb_client_club_invitation_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bgs_low_pb_client_club_membership_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClubMembershipFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_club_membership_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClubMembershipSubscribeOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_club_membership_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClubMembershipGetStateOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_club_membership_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClubMembershipDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_club_membership_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClubMembershipState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_club_membership_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClubPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_club_membership_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClubSharedSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_club_membership_types_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClubSharedSettingsOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_club_membership_types_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClubSharedSettingsAssignment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bgs_low_pb_client_club_membership_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bgs_low_pb_client_club_membership_types_proto_goTypes,
		DependencyIndexes: file_bgs_low_pb_client_club_membership_types_proto_depIdxs,
		MessageInfos:      file_bgs_low_pb_client_club_membership_types_proto_msgTypes,
	}.Build()
	File_bgs_low_pb_client_club_membership_types_proto = out.File
	file_bgs_low_pb_client_club_membership_types_proto_rawDesc = nil
	file_bgs_low_pb_client_club_membership_types_proto_goTypes = nil
	file_bgs_low_pb_client_club_membership_types_proto_depIdxs = nil
}
