// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: bgs/low/pb/client/club_enum.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrivacyLevel int32

const (
	PrivacyLevel_PRIVACY_LEVEL_CLOSED          PrivacyLevel = 0
	PrivacyLevel_PRIVACY_LEVEL_OPEN_INVITATION PrivacyLevel = 1
	PrivacyLevel_PRIVACY_LEVEL_OPEN_TICKET     PrivacyLevel = 2
	PrivacyLevel_PRIVACY_LEVEL_OPEN            PrivacyLevel = 3
)

// Enum value maps for PrivacyLevel.
var (
	PrivacyLevel_name = map[int32]string{
		0: "PRIVACY_LEVEL_CLOSED",
		1: "PRIVACY_LEVEL_OPEN_INVITATION",
		2: "PRIVACY_LEVEL_OPEN_TICKET",
		3: "PRIVACY_LEVEL_OPEN",
	}
	PrivacyLevel_value = map[string]int32{
		"PRIVACY_LEVEL_CLOSED":          0,
		"PRIVACY_LEVEL_OPEN_INVITATION": 1,
		"PRIVACY_LEVEL_OPEN_TICKET":     2,
		"PRIVACY_LEVEL_OPEN":            3,
	}
)

func (x PrivacyLevel) Enum() *PrivacyLevel {
	p := new(PrivacyLevel)
	*p = x
	return p
}

func (x PrivacyLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivacyLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_club_enum_proto_enumTypes[0].Descriptor()
}

func (PrivacyLevel) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_club_enum_proto_enumTypes[0]
}

func (x PrivacyLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PrivacyLevel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PrivacyLevel(num)
	return nil
}

// Deprecated: Use PrivacyLevel.Descriptor instead.
func (PrivacyLevel) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_enum_proto_rawDescGZIP(), []int{0}
}

type VisibilityLevel int32

const (
	VisibilityLevel_VISIBILITY_LEVEL_PRIVATE VisibilityLevel = 0
	VisibilityLevel_VISIBILITY_LEVEL_PUBLIC  VisibilityLevel = 1
)

// Enum value maps for VisibilityLevel.
var (
	VisibilityLevel_name = map[int32]string{
		0: "VISIBILITY_LEVEL_PRIVATE",
		1: "VISIBILITY_LEVEL_PUBLIC",
	}
	VisibilityLevel_value = map[string]int32{
		"VISIBILITY_LEVEL_PRIVATE": 0,
		"VISIBILITY_LEVEL_PUBLIC":  1,
	}
)

func (x VisibilityLevel) Enum() *VisibilityLevel {
	p := new(VisibilityLevel)
	*p = x
	return p
}

func (x VisibilityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisibilityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_club_enum_proto_enumTypes[1].Descriptor()
}

func (VisibilityLevel) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_club_enum_proto_enumTypes[1]
}

func (x VisibilityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *VisibilityLevel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = VisibilityLevel(num)
	return nil
}

// Deprecated: Use VisibilityLevel.Descriptor instead.
func (VisibilityLevel) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_enum_proto_rawDescGZIP(), []int{1}
}

type ClubRemovedReason int32

const (
	ClubRemovedReason_CLUB_REMOVED_REASON_NONE                      ClubRemovedReason = 0
	ClubRemovedReason_CLUB_REMOVED_REASON_MEMBER_LEFT               ClubRemovedReason = 1
	ClubRemovedReason_CLUB_REMOVED_REASON_MEMBER_KICKED             ClubRemovedReason = 2
	ClubRemovedReason_CLUB_REMOVED_REASON_MEMBER_BANNED             ClubRemovedReason = 3
	ClubRemovedReason_CLUB_REMOVED_REASON_MEMBER_REMOVED_BY_SERVICE ClubRemovedReason = 4
	ClubRemovedReason_CLUB_REMOVED_REASON_DESTROYED_BY_MEMBER       ClubRemovedReason = 5
	ClubRemovedReason_CLUB_REMOVED_REASON_DESTROYED_BY_SERVICE      ClubRemovedReason = 6
)

// Enum value maps for ClubRemovedReason.
var (
	ClubRemovedReason_name = map[int32]string{
		0: "CLUB_REMOVED_REASON_NONE",
		1: "CLUB_REMOVED_REASON_MEMBER_LEFT",
		2: "CLUB_REMOVED_REASON_MEMBER_KICKED",
		3: "CLUB_REMOVED_REASON_MEMBER_BANNED",
		4: "CLUB_REMOVED_REASON_MEMBER_REMOVED_BY_SERVICE",
		5: "CLUB_REMOVED_REASON_DESTROYED_BY_MEMBER",
		6: "CLUB_REMOVED_REASON_DESTROYED_BY_SERVICE",
	}
	ClubRemovedReason_value = map[string]int32{
		"CLUB_REMOVED_REASON_NONE":                      0,
		"CLUB_REMOVED_REASON_MEMBER_LEFT":               1,
		"CLUB_REMOVED_REASON_MEMBER_KICKED":             2,
		"CLUB_REMOVED_REASON_MEMBER_BANNED":             3,
		"CLUB_REMOVED_REASON_MEMBER_REMOVED_BY_SERVICE": 4,
		"CLUB_REMOVED_REASON_DESTROYED_BY_MEMBER":       5,
		"CLUB_REMOVED_REASON_DESTROYED_BY_SERVICE":      6,
	}
)

func (x ClubRemovedReason) Enum() *ClubRemovedReason {
	p := new(ClubRemovedReason)
	*p = x
	return p
}

func (x ClubRemovedReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClubRemovedReason) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_club_enum_proto_enumTypes[2].Descriptor()
}

func (ClubRemovedReason) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_club_enum_proto_enumTypes[2]
}

func (x ClubRemovedReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ClubRemovedReason) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ClubRemovedReason(num)
	return nil
}

// Deprecated: Use ClubRemovedReason.Descriptor instead.
func (ClubRemovedReason) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_enum_proto_rawDescGZIP(), []int{2}
}

type StreamVoiceLevel int32

const (
	StreamVoiceLevel_VOICE_LEVEL_DISABLED     StreamVoiceLevel = 0
	StreamVoiceLevel_VOICE_LEVEL_PUSH_TO_TALK StreamVoiceLevel = 1
	StreamVoiceLevel_VOICE_LEVEL_OPEN_MIC     StreamVoiceLevel = 2
)

// Enum value maps for StreamVoiceLevel.
var (
	StreamVoiceLevel_name = map[int32]string{
		0: "VOICE_LEVEL_DISABLED",
		1: "VOICE_LEVEL_PUSH_TO_TALK",
		2: "VOICE_LEVEL_OPEN_MIC",
	}
	StreamVoiceLevel_value = map[string]int32{
		"VOICE_LEVEL_DISABLED":     0,
		"VOICE_LEVEL_PUSH_TO_TALK": 1,
		"VOICE_LEVEL_OPEN_MIC":     2,
	}
)

func (x StreamVoiceLevel) Enum() *StreamVoiceLevel {
	p := new(StreamVoiceLevel)
	*p = x
	return p
}

func (x StreamVoiceLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamVoiceLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_club_enum_proto_enumTypes[3].Descriptor()
}

func (StreamVoiceLevel) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_club_enum_proto_enumTypes[3]
}

func (x StreamVoiceLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StreamVoiceLevel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StreamVoiceLevel(num)
	return nil
}

// Deprecated: Use StreamVoiceLevel.Descriptor instead.
func (StreamVoiceLevel) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_enum_proto_rawDescGZIP(), []int{3}
}

type VoiceMicrophoneState int32

const (
	VoiceMicrophoneState_MICROPHONE_STATE_NORMAL    VoiceMicrophoneState = 0
	VoiceMicrophoneState_MICROPHONE_STATE_SELF_MUTE VoiceMicrophoneState = 1
	VoiceMicrophoneState_MICROPHONE_STATE_SELF_DEAF VoiceMicrophoneState = 2
)

// Enum value maps for VoiceMicrophoneState.
var (
	VoiceMicrophoneState_name = map[int32]string{
		0: "MICROPHONE_STATE_NORMAL",
		1: "MICROPHONE_STATE_SELF_MUTE",
		2: "MICROPHONE_STATE_SELF_DEAF",
	}
	VoiceMicrophoneState_value = map[string]int32{
		"MICROPHONE_STATE_NORMAL":    0,
		"MICROPHONE_STATE_SELF_MUTE": 1,
		"MICROPHONE_STATE_SELF_DEAF": 2,
	}
)

func (x VoiceMicrophoneState) Enum() *VoiceMicrophoneState {
	p := new(VoiceMicrophoneState)
	*p = x
	return p
}

func (x VoiceMicrophoneState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceMicrophoneState) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_club_enum_proto_enumTypes[4].Descriptor()
}

func (VoiceMicrophoneState) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_club_enum_proto_enumTypes[4]
}

func (x VoiceMicrophoneState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *VoiceMicrophoneState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = VoiceMicrophoneState(num)
	return nil
}

// Deprecated: Use VoiceMicrophoneState.Descriptor instead.
func (VoiceMicrophoneState) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_enum_proto_rawDescGZIP(), []int{4}
}

type PresenceLevel int32

const (
	PresenceLevel_PRESENCE_LEVEL_NONE  PresenceLevel = 0
	PresenceLevel_PRESENCE_LEVEL_BASIC PresenceLevel = 1
	PresenceLevel_PRESENCE_LEVEL_RICH  PresenceLevel = 2
)

// Enum value maps for PresenceLevel.
var (
	PresenceLevel_name = map[int32]string{
		0: "PRESENCE_LEVEL_NONE",
		1: "PRESENCE_LEVEL_BASIC",
		2: "PRESENCE_LEVEL_RICH",
	}
	PresenceLevel_value = map[string]int32{
		"PRESENCE_LEVEL_NONE":  0,
		"PRESENCE_LEVEL_BASIC": 1,
		"PRESENCE_LEVEL_RICH":  2,
	}
)

func (x PresenceLevel) Enum() *PresenceLevel {
	p := new(PresenceLevel)
	*p = x
	return p
}

func (x PresenceLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresenceLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_club_enum_proto_enumTypes[5].Descriptor()
}

func (PresenceLevel) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_club_enum_proto_enumTypes[5]
}

func (x PresenceLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PresenceLevel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PresenceLevel(num)
	return nil
}

// Deprecated: Use PresenceLevel.Descriptor instead.
func (PresenceLevel) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_enum_proto_rawDescGZIP(), []int{5}
}

type WhisperLevel int32

const (
	WhisperLevel_WHISPER_LEVEL_OPEN       WhisperLevel = 0
	WhisperLevel_WHISPER_LEVEL_RESTRICTED WhisperLevel = 1
)

// Enum value maps for WhisperLevel.
var (
	WhisperLevel_name = map[int32]string{
		0: "WHISPER_LEVEL_OPEN",
		1: "WHISPER_LEVEL_RESTRICTED",
	}
	WhisperLevel_value = map[string]int32{
		"WHISPER_LEVEL_OPEN":       0,
		"WHISPER_LEVEL_RESTRICTED": 1,
	}
)

func (x WhisperLevel) Enum() *WhisperLevel {
	p := new(WhisperLevel)
	*p = x
	return p
}

func (x WhisperLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WhisperLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_club_enum_proto_enumTypes[6].Descriptor()
}

func (WhisperLevel) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_club_enum_proto_enumTypes[6]
}

func (x WhisperLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *WhisperLevel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = WhisperLevel(num)
	return nil
}

// Deprecated: Use WhisperLevel.Descriptor instead.
func (WhisperLevel) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_enum_proto_rawDescGZIP(), []int{6}
}

type StreamNotificationFilter int32

const (
	StreamNotificationFilter_STREAM_NOTIFICATION_FILTER_NONE    StreamNotificationFilter = 0
	StreamNotificationFilter_STREAM_NOTIFICATION_FILTER_MENTION StreamNotificationFilter = 1
	StreamNotificationFilter_STREAM_NOTIFICATION_FILTER_ALL     StreamNotificationFilter = 2
)

// Enum value maps for StreamNotificationFilter.
var (
	StreamNotificationFilter_name = map[int32]string{
		0: "STREAM_NOTIFICATION_FILTER_NONE",
		1: "STREAM_NOTIFICATION_FILTER_MENTION",
		2: "STREAM_NOTIFICATION_FILTER_ALL",
	}
	StreamNotificationFilter_value = map[string]int32{
		"STREAM_NOTIFICATION_FILTER_NONE":    0,
		"STREAM_NOTIFICATION_FILTER_MENTION": 1,
		"STREAM_NOTIFICATION_FILTER_ALL":     2,
	}
)

func (x StreamNotificationFilter) Enum() *StreamNotificationFilter {
	p := new(StreamNotificationFilter)
	*p = x
	return p
}

func (x StreamNotificationFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamNotificationFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_club_enum_proto_enumTypes[7].Descriptor()
}

func (StreamNotificationFilter) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_club_enum_proto_enumTypes[7]
}

func (x StreamNotificationFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StreamNotificationFilter) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StreamNotificationFilter(num)
	return nil
}

// Deprecated: Use StreamNotificationFilter.Descriptor instead.
func (StreamNotificationFilter) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_enum_proto_rawDescGZIP(), []int{7}
}

type JoinClubSource int32

const (
	JoinClubSource_JOIN_CLUB_SOURCE_NONE                JoinClubSource = 0
	JoinClubSource_JOIN_CLUB_SOURCE_CLUB_FINDER         JoinClubSource = 1
	JoinClubSource_JOIN_CLUB_SOURCE_CLUB_RECOMMENDATION JoinClubSource = 2
)

// Enum value maps for JoinClubSource.
var (
	JoinClubSource_name = map[int32]string{
		0: "JOIN_CLUB_SOURCE_NONE",
		1: "JOIN_CLUB_SOURCE_CLUB_FINDER",
		2: "JOIN_CLUB_SOURCE_CLUB_RECOMMENDATION",
	}
	JoinClubSource_value = map[string]int32{
		"JOIN_CLUB_SOURCE_NONE":                0,
		"JOIN_CLUB_SOURCE_CLUB_FINDER":         1,
		"JOIN_CLUB_SOURCE_CLUB_RECOMMENDATION": 2,
	}
)

func (x JoinClubSource) Enum() *JoinClubSource {
	p := new(JoinClubSource)
	*p = x
	return p
}

func (x JoinClubSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinClubSource) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_club_enum_proto_enumTypes[8].Descriptor()
}

func (JoinClubSource) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_club_enum_proto_enumTypes[8]
}

func (x JoinClubSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *JoinClubSource) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = JoinClubSource(num)
	return nil
}

// Deprecated: Use JoinClubSource.Descriptor instead.
func (JoinClubSource) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_club_enum_proto_rawDescGZIP(), []int{8}
}

var File_bgs_low_pb_client_club_enum_proto protoreflect.FileDescriptor

var file_bgs_low_pb_client_club_enum_proto_rawDesc = []byte{
	0x0a, 0x21, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6c, 0x75, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2a, 0x82, 0x01, 0x0a, 0x0c, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x63, 0x79, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52,
	0x49, 0x56, 0x41, 0x43, 0x59, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x43, 0x4c, 0x4f, 0x53,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x50, 0x52, 0x49, 0x56, 0x41, 0x43, 0x59, 0x5f,
	0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x5f, 0x49, 0x4e, 0x56, 0x49, 0x54,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x50, 0x52, 0x49, 0x56, 0x41,
	0x43, 0x59, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x5f, 0x54, 0x49,
	0x43, 0x4b, 0x45, 0x54, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x52, 0x49, 0x56, 0x41, 0x43,
	0x59, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x03, 0x2a, 0x4c,
	0x0a, 0x0f, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x1c, 0x0a, 0x18, 0x56, 0x49, 0x53, 0x49, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f,
	0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12,
	0x1b, 0x0a, 0x17, 0x56, 0x49, 0x53, 0x49, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x4c, 0x45,
	0x56, 0x45, 0x4c, 0x5f, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x10, 0x01, 0x2a, 0xb2, 0x02, 0x0a,
	0x11, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4c, 0x55, 0x42, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56,
	0x45, 0x44, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00,
	0x12, 0x23, 0x0a, 0x1f, 0x43, 0x4c, 0x55, 0x42, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x44,
	0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x4c,
	0x45, 0x46, 0x54, 0x10, 0x01, 0x12, 0x25, 0x0a, 0x21, 0x43, 0x4c, 0x55, 0x42, 0x5f, 0x52, 0x45,
	0x4d, 0x4f, 0x56, 0x45, 0x44, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x4d, 0x45, 0x4d,
	0x42, 0x45, 0x52, 0x5f, 0x4b, 0x49, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x02, 0x12, 0x25, 0x0a, 0x21,
	0x43, 0x4c, 0x55, 0x42, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x44, 0x5f, 0x52, 0x45, 0x41,
	0x53, 0x4f, 0x4e, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x42, 0x41, 0x4e, 0x4e, 0x45,
	0x44, 0x10, 0x03, 0x12, 0x31, 0x0a, 0x2d, 0x43, 0x4c, 0x55, 0x42, 0x5f, 0x52, 0x45, 0x4d, 0x4f,
	0x56, 0x45, 0x44, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45,
	0x52, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x44, 0x5f, 0x42, 0x59, 0x5f, 0x53, 0x45, 0x52,
	0x56, 0x49, 0x43, 0x45, 0x10, 0x04, 0x12, 0x2b, 0x0a, 0x27, 0x43, 0x4c, 0x55, 0x42, 0x5f, 0x52,
	0x45, 0x4d, 0x4f, 0x56, 0x45, 0x44, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x44, 0x45,
	0x53, 0x54, 0x52, 0x4f, 0x59, 0x45, 0x44, 0x5f, 0x42, 0x59, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45,
	0x52, 0x10, 0x05, 0x12, 0x2c, 0x0a, 0x28, 0x43, 0x4c, 0x55, 0x42, 0x5f, 0x52, 0x45, 0x4d, 0x4f,
	0x56, 0x45, 0x44, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x53, 0x54, 0x52,
	0x4f, 0x59, 0x45, 0x44, 0x5f, 0x42, 0x59, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10,
	0x06, 0x2a, 0x64, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x6f, 0x69, 0x63, 0x65,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x14, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x5f, 0x4c,
	0x45, 0x56, 0x45, 0x4c, 0x5f, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x1c, 0x0a, 0x18, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x50,
	0x55, 0x53, 0x48, 0x5f, 0x54, 0x4f, 0x5f, 0x54, 0x41, 0x4c, 0x4b, 0x10, 0x01, 0x12, 0x18, 0x0a,
	0x14, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x4f, 0x50, 0x45,
	0x4e, 0x5f, 0x4d, 0x49, 0x43, 0x10, 0x02, 0x2a, 0x73, 0x0a, 0x14, 0x56, 0x6f, 0x69, 0x63, 0x65,
	0x4d, 0x69, 0x63, 0x72, 0x6f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x1b, 0x0a, 0x17, 0x4d, 0x49, 0x43, 0x52, 0x4f, 0x50, 0x48, 0x4f, 0x4e, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a,
	0x4d, 0x49, 0x43, 0x52, 0x4f, 0x50, 0x48, 0x4f, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x53, 0x45, 0x4c, 0x46, 0x5f, 0x4d, 0x55, 0x54, 0x45, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a,
	0x4d, 0x49, 0x43, 0x52, 0x4f, 0x50, 0x48, 0x4f, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x53, 0x45, 0x4c, 0x46, 0x5f, 0x44, 0x45, 0x41, 0x46, 0x10, 0x02, 0x2a, 0x5b, 0x0a, 0x0d,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x17, 0x0a,
	0x13, 0x50, 0x52, 0x45, 0x53, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x45, 0x53, 0x45, 0x4e,
	0x43, 0x45, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x42, 0x41, 0x53, 0x49, 0x43, 0x10, 0x01,
	0x12, 0x17, 0x0a, 0x13, 0x50, 0x52, 0x45, 0x53, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x4c, 0x45, 0x56,
	0x45, 0x4c, 0x5f, 0x52, 0x49, 0x43, 0x48, 0x10, 0x02, 0x2a, 0x44, 0x0a, 0x0c, 0x57, 0x68, 0x69,
	0x73, 0x70, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x12, 0x57, 0x48, 0x49,
	0x53, 0x50, 0x45, 0x52, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10,
	0x00, 0x12, 0x1c, 0x0a, 0x18, 0x57, 0x48, 0x49, 0x53, 0x50, 0x45, 0x52, 0x5f, 0x4c, 0x45, 0x56,
	0x45, 0x4c, 0x5f, 0x52, 0x45, 0x53, 0x54, 0x52, 0x49, 0x43, 0x54, 0x45, 0x44, 0x10, 0x01, 0x2a,
	0x8b, 0x01, 0x0a, 0x18, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x1f,
	0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x26, 0x0a, 0x22, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x4e, 0x4f, 0x54, 0x49,
	0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f,
	0x4d, 0x45, 0x4e, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e, 0x53, 0x54, 0x52,
	0x45, 0x41, 0x4d, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x02, 0x2a, 0x77, 0x0a,
	0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x62, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x19, 0x0a, 0x15, 0x4a, 0x4f, 0x49, 0x4e, 0x5f, 0x43, 0x4c, 0x55, 0x42, 0x5f, 0x53, 0x4f, 0x55,
	0x52, 0x43, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x4a, 0x4f,
	0x49, 0x4e, 0x5f, 0x43, 0x4c, 0x55, 0x42, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x43,
	0x4c, 0x55, 0x42, 0x5f, 0x46, 0x49, 0x4e, 0x44, 0x45, 0x52, 0x10, 0x01, 0x12, 0x28, 0x0a, 0x24,
	0x4a, 0x4f, 0x49, 0x4e, 0x5f, 0x43, 0x4c, 0x55, 0x42, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45,
	0x5f, 0x43, 0x4c, 0x55, 0x42, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x44, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6a, 0x62, 0x72, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2f, 0x6c,
	0x6f, 0x67, 0x70, 0x72, 0x6f, 0x78, 0x2f, 0x62, 0x6e, 0x65, 0x74, 0x2f, 0x62, 0x67, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6c, 0x75, 0x62, 0x2f, 0x76, 0x31,
}

var (
	file_bgs_low_pb_client_club_enum_proto_rawDescOnce sync.Once
	file_bgs_low_pb_client_club_enum_proto_rawDescData = file_bgs_low_pb_client_club_enum_proto_rawDesc
)

func file_bgs_low_pb_client_club_enum_proto_rawDescGZIP() []byte {
	file_bgs_low_pb_client_club_enum_proto_rawDescOnce.Do(func() {
		file_bgs_low_pb_client_club_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_bgs_low_pb_client_club_enum_proto_rawDescData)
	})
	return file_bgs_low_pb_client_club_enum_proto_rawDescData
}

var file_bgs_low_pb_client_club_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_bgs_low_pb_client_club_enum_proto_goTypes = []interface{}{
	(PrivacyLevel)(0),             // 0: bgs.protocol.club.v1.PrivacyLevel
	(VisibilityLevel)(0),          // 1: bgs.protocol.club.v1.VisibilityLevel
	(ClubRemovedReason)(0),        // 2: bgs.protocol.club.v1.ClubRemovedReason
	(StreamVoiceLevel)(0),         // 3: bgs.protocol.club.v1.StreamVoiceLevel
	(VoiceMicrophoneState)(0),     // 4: bgs.protocol.club.v1.VoiceMicrophoneState
	(PresenceLevel)(0),            // 5: bgs.protocol.club.v1.PresenceLevel
	(WhisperLevel)(0),             // 6: bgs.protocol.club.v1.WhisperLevel
	(StreamNotificationFilter)(0), // 7: bgs.protocol.club.v1.StreamNotificationFilter
	(JoinClubSource)(0),           // 8: bgs.protocol.club.v1.JoinClubSource
}
var file_bgs_low_pb_client_club_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bgs_low_pb_client_club_enum_proto_init() }
func file_bgs_low_pb_client_club_enum_proto_init() {
	if File_bgs_low_pb_client_club_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bgs_low_pb_client_club_enum_proto_rawDesc,
			NumEnums:      9,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bgs_low_pb_client_club_enum_proto_goTypes,
		DependencyIndexes: file_bgs_low_pb_client_club_enum_proto_depIdxs,
		EnumInfos:         file_bgs_low_pb_client_club_enum_proto_enumTypes,
	}.Build()
	File_bgs_low_pb_client_club_enum_proto = out.File
	file_bgs_low_pb_client_club_enum_proto_rawDesc = nil
	file_bgs_low_pb_client_club_enum_proto_goTypes = nil
	file_bgs_low_pb_client_club_enum_proto_depIdxs = nil
}
