// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: bgs/low/pb/client/embed_types.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    *string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Width  *uint32 `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	Height *uint32 `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
}

func (x *EmbedImage) Reset() {
	*x = EmbedImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_embed_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedImage) ProtoMessage() {}

func (x *EmbedImage) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_embed_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedImage.ProtoReflect.Descriptor instead.
func (*EmbedImage) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_embed_types_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedImage) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *EmbedImage) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *EmbedImage) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

type Provider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (x *Provider) Reset() {
	*x = Provider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_embed_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_embed_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_embed_types_proto_rawDescGZIP(), []int{1}
}

func (x *Provider) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type EmbedHTML struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content *string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	Width   *uint32 `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	Height  *uint32 `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
}

func (x *EmbedHTML) Reset() {
	*x = EmbedHTML{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_embed_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbedHTML) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedHTML) ProtoMessage() {}

func (x *EmbedHTML) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_embed_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedHTML.ProtoReflect.Descriptor instead.
func (*EmbedHTML) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_embed_types_proto_rawDescGZIP(), []int{2}
}

func (x *EmbedHTML) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *EmbedHTML) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *EmbedHTML) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

type EmbedInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       *string     `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Type        *string     `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	OriginalUrl *string     `protobuf:"bytes,3,opt,name=original_url,json=originalUrl" json:"original_url,omitempty"`
	Thumbnail   *EmbedImage `protobuf:"bytes,4,opt,name=thumbnail" json:"thumbnail,omitempty"`
	Provider    *Provider   `protobuf:"bytes,5,opt,name=provider" json:"provider,omitempty"`
	Description *string     `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	Html        *EmbedHTML  `protobuf:"bytes,8,opt,name=html" json:"html,omitempty"`
}

func (x *EmbedInfo) Reset() {
	*x = EmbedInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_embed_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbedInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedInfo) ProtoMessage() {}

func (x *EmbedInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_embed_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedInfo.ProtoReflect.Descriptor instead.
func (*EmbedInfo) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_embed_types_proto_rawDescGZIP(), []int{3}
}

func (x *EmbedInfo) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *EmbedInfo) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *EmbedInfo) GetOriginalUrl() string {
	if x != nil && x.OriginalUrl != nil {
		return *x.OriginalUrl
	}
	return ""
}

func (x *EmbedInfo) GetThumbnail() *EmbedImage {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

func (x *EmbedInfo) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *EmbedInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *EmbedInfo) GetHtml() *EmbedHTML {
	if x != nil {
		return x.Html
	}
	return nil
}

var File_bgs_low_pb_client_embed_types_proto protoreflect.FileDescriptor

var file_bgs_low_pb_client_embed_types_proto_rawDesc = []byte{
	0x0a, 0x23, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x22, 0x4c, 0x0a, 0x0a, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x1e, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x53, 0x0a, 0x09, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x48, 0x54, 0x4d, 0x4c, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x93, 0x02, 0x0a, 0x09, 0x45, 0x6d, 0x62, 0x65, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72,
	0x6c, 0x12, 0x36, 0x0a, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x09,
	0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x32, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x67,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2b, 0x0a, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x6d, 0x62,
	0x65, 0x64, 0x48, 0x54, 0x4d, 0x4c, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x42, 0x30, 0x5a, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6a, 0x62, 0x72, 0x69,
	0x67, 0x61, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x78, 0x2f, 0x62, 0x6e, 0x65,
	0x74, 0x2f, 0x62, 0x67, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
}

var (
	file_bgs_low_pb_client_embed_types_proto_rawDescOnce sync.Once
	file_bgs_low_pb_client_embed_types_proto_rawDescData = file_bgs_low_pb_client_embed_types_proto_rawDesc
)

func file_bgs_low_pb_client_embed_types_proto_rawDescGZIP() []byte {
	file_bgs_low_pb_client_embed_types_proto_rawDescOnce.Do(func() {
		file_bgs_low_pb_client_embed_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_bgs_low_pb_client_embed_types_proto_rawDescData)
	})
	return file_bgs_low_pb_client_embed_types_proto_rawDescData
}

var file_bgs_low_pb_client_embed_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bgs_low_pb_client_embed_types_proto_goTypes = []interface{}{
	(*EmbedImage)(nil), // 0: bgs.protocol.EmbedImage
	(*Provider)(nil),   // 1: bgs.protocol.Provider
	(*EmbedHTML)(nil),  // 2: bgs.protocol.EmbedHTML
	(*EmbedInfo)(nil),  // 3: bgs.protocol.EmbedInfo
}
var file_bgs_low_pb_client_embed_types_proto_depIdxs = []int32{
	0, // 0: bgs.protocol.EmbedInfo.thumbnail:type_name -> bgs.protocol.EmbedImage
	1, // 1: bgs.protocol.EmbedInfo.provider:type_name -> bgs.protocol.Provider
	2, // 2: bgs.protocol.EmbedInfo.html:type_name -> bgs.protocol.EmbedHTML
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bgs_low_pb_client_embed_types_proto_init() }
func file_bgs_low_pb_client_embed_types_proto_init() {
	if File_bgs_low_pb_client_embed_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bgs_low_pb_client_embed_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbedImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_embed_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Provider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_embed_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbedHTML); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_embed_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbedInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bgs_low_pb_client_embed_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bgs_low_pb_client_embed_types_proto_goTypes,
		DependencyIndexes: file_bgs_low_pb_client_embed_types_proto_depIdxs,
		MessageInfos:      file_bgs_low_pb_client_embed_types_proto_msgTypes,
	}.Build()
	File_bgs_low_pb_client_embed_types_proto = out.File
	file_bgs_low_pb_client_embed_types_proto_rawDesc = nil
	file_bgs_low_pb_client_embed_types_proto_goTypes = nil
	file_bgs_low_pb_client_embed_types_proto_depIdxs = nil
}
