// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: bgs/low/pb/client/event_view_types.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventOrder int32

const (
	EventOrder_EVENT_DESCENDING EventOrder = 0
	EventOrder_EVENT_ASCENDING  EventOrder = 1
)

// Enum value maps for EventOrder.
var (
	EventOrder_name = map[int32]string{
		0: "EVENT_DESCENDING",
		1: "EVENT_ASCENDING",
	}
	EventOrder_value = map[string]int32{
		"EVENT_DESCENDING": 0,
		"EVENT_ASCENDING":  1,
	}
)

func (x EventOrder) Enum() *EventOrder {
	p := new(EventOrder)
	*p = x
	return p
}

func (x EventOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_event_view_types_proto_enumTypes[0].Descriptor()
}

func (EventOrder) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_event_view_types_proto_enumTypes[0]
}

func (x EventOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EventOrder) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EventOrder(num)
	return nil
}

// Deprecated: Use EventOrder.Descriptor instead.
func (EventOrder) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_event_view_types_proto_rawDescGZIP(), []int{0}
}

type GetEventOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FetchFrom  *uint64     `protobuf:"varint,1,opt,name=fetch_from,json=fetchFrom" json:"fetch_from,omitempty"`
	FetchUntil *uint64     `protobuf:"varint,2,opt,name=fetch_until,json=fetchUntil" json:"fetch_until,omitempty"`
	MaxEvents  *uint32     `protobuf:"varint,3,opt,name=max_events,json=maxEvents" json:"max_events,omitempty"`
	Order      *EventOrder `protobuf:"varint,4,opt,name=order,enum=bgs.protocol.EventOrder" json:"order,omitempty"`
}

func (x *GetEventOptions) Reset() {
	*x = GetEventOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_event_view_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventOptions) ProtoMessage() {}

func (x *GetEventOptions) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_event_view_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventOptions.ProtoReflect.Descriptor instead.
func (*GetEventOptions) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_event_view_types_proto_rawDescGZIP(), []int{0}
}

func (x *GetEventOptions) GetFetchFrom() uint64 {
	if x != nil && x.FetchFrom != nil {
		return *x.FetchFrom
	}
	return 0
}

func (x *GetEventOptions) GetFetchUntil() uint64 {
	if x != nil && x.FetchUntil != nil {
		return *x.FetchUntil
	}
	return 0
}

func (x *GetEventOptions) GetMaxEvents() uint32 {
	if x != nil && x.MaxEvents != nil {
		return *x.MaxEvents
	}
	return 0
}

func (x *GetEventOptions) GetOrder() EventOrder {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return EventOrder_EVENT_DESCENDING
}

type ViewMarker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastReadTime    *uint64 `protobuf:"varint,1,opt,name=last_read_time,json=lastReadTime" json:"last_read_time,omitempty"`
	LastMessageTime *uint64 `protobuf:"varint,2,opt,name=last_message_time,json=lastMessageTime" json:"last_message_time,omitempty"`
}

func (x *ViewMarker) Reset() {
	*x = ViewMarker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_event_view_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewMarker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarker) ProtoMessage() {}

func (x *ViewMarker) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_event_view_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarker.ProtoReflect.Descriptor instead.
func (*ViewMarker) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_event_view_types_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarker) GetLastReadTime() uint64 {
	if x != nil && x.LastReadTime != nil {
		return *x.LastReadTime
	}
	return 0
}

func (x *ViewMarker) GetLastMessageTime() uint64 {
	if x != nil && x.LastMessageTime != nil {
		return *x.LastMessageTime
	}
	return 0
}

var File_bgs_low_pb_client_event_view_types_proto protoreflect.FileDescriptor

var file_bgs_low_pb_client_event_view_types_proto_rawDesc = []byte{
	0x0a, 0x28, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x67, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xa0, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x66, 0x65, 0x74, 0x63, 0x68, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x66,
	0x65, 0x74, 0x63, 0x68, 0x5f, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x66, 0x65, 0x74, 0x63, 0x68, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x61, 0x78, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x6d, 0x61, 0x78, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2e, 0x0a, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x62, 0x67, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x5e, 0x0a, 0x0a, 0x56,
	0x69, 0x65, 0x77, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x2a, 0x0a, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x2a, 0x37, 0x0a, 0x0a, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x56, 0x45,
	0x4e, 0x54, 0x5f, 0x44, 0x45, 0x53, 0x43, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x53, 0x43, 0x45, 0x4e, 0x44, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x6a, 0x62, 0x72, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67,
	0x70, 0x72, 0x6f, 0x78, 0x2f, 0x62, 0x6e, 0x65, 0x74, 0x2f, 0x62, 0x67, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
}

var (
	file_bgs_low_pb_client_event_view_types_proto_rawDescOnce sync.Once
	file_bgs_low_pb_client_event_view_types_proto_rawDescData = file_bgs_low_pb_client_event_view_types_proto_rawDesc
)

func file_bgs_low_pb_client_event_view_types_proto_rawDescGZIP() []byte {
	file_bgs_low_pb_client_event_view_types_proto_rawDescOnce.Do(func() {
		file_bgs_low_pb_client_event_view_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_bgs_low_pb_client_event_view_types_proto_rawDescData)
	})
	return file_bgs_low_pb_client_event_view_types_proto_rawDescData
}

var file_bgs_low_pb_client_event_view_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bgs_low_pb_client_event_view_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bgs_low_pb_client_event_view_types_proto_goTypes = []interface{}{
	(EventOrder)(0),         // 0: bgs.protocol.EventOrder
	(*GetEventOptions)(nil), // 1: bgs.protocol.GetEventOptions
	(*ViewMarker)(nil),      // 2: bgs.protocol.ViewMarker
}
var file_bgs_low_pb_client_event_view_types_proto_depIdxs = []int32{
	0, // 0: bgs.protocol.GetEventOptions.order:type_name -> bgs.protocol.EventOrder
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bgs_low_pb_client_event_view_types_proto_init() }
func file_bgs_low_pb_client_event_view_types_proto_init() {
	if File_bgs_low_pb_client_event_view_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bgs_low_pb_client_event_view_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_event_view_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewMarker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bgs_low_pb_client_event_view_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bgs_low_pb_client_event_view_types_proto_goTypes,
		DependencyIndexes: file_bgs_low_pb_client_event_view_types_proto_depIdxs,
		EnumInfos:         file_bgs_low_pb_client_event_view_types_proto_enumTypes,
		MessageInfos:      file_bgs_low_pb_client_event_view_types_proto_msgTypes,
	}.Build()
	File_bgs_low_pb_client_event_view_types_proto = out.File
	file_bgs_low_pb_client_event_view_types_proto_rawDesc = nil
	file_bgs_low_pb_client_event_view_types_proto_goTypes = nil
	file_bgs_low_pb_client_event_view_types_proto_depIdxs = nil
}
