// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: bgs/low/pb/client/global_extensions/field_options.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogOption int32

const (
	LogOption_HIDDEN LogOption = 1
	LogOption_HEX    LogOption = 2
)

// Enum value maps for LogOption.
var (
	LogOption_name = map[int32]string{
		1: "HIDDEN",
		2: "HEX",
	}
	LogOption_value = map[string]int32{
		"HIDDEN": 1,
		"HEX":    2,
	}
)

func (x LogOption) Enum() *LogOption {
	p := new(LogOption)
	*p = x
	return p
}

func (x LogOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogOption) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_enumTypes[0].Descriptor()
}

func (LogOption) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_global_extensions_field_options_proto_enumTypes[0]
}

func (x LogOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *LogOption) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = LogOption(num)
	return nil
}

// Deprecated: Use LogOption.Descriptor instead.
func (LogOption) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescGZIP(), []int{0}
}

type EntityIdRestriction_Kind int32

const (
	EntityIdRestriction_ANY                     EntityIdRestriction_Kind = 0
	EntityIdRestriction_ACCOUNT                 EntityIdRestriction_Kind = 1
	EntityIdRestriction_GAME_ACCOUNT            EntityIdRestriction_Kind = 2
	EntityIdRestriction_ACCOUNT_OR_GAME_ACCOUNT EntityIdRestriction_Kind = 3
	EntityIdRestriction_SERVICE                 EntityIdRestriction_Kind = 4
	EntityIdRestriction_CHANNEL                 EntityIdRestriction_Kind = 5
)

// Enum value maps for EntityIdRestriction_Kind.
var (
	EntityIdRestriction_Kind_name = map[int32]string{
		0: "ANY",
		1: "ACCOUNT",
		2: "GAME_ACCOUNT",
		3: "ACCOUNT_OR_GAME_ACCOUNT",
		4: "SERVICE",
		5: "CHANNEL",
	}
	EntityIdRestriction_Kind_value = map[string]int32{
		"ANY":                     0,
		"ACCOUNT":                 1,
		"GAME_ACCOUNT":            2,
		"ACCOUNT_OR_GAME_ACCOUNT": 3,
		"SERVICE":                 4,
		"CHANNEL":                 5,
	}
)

func (x EntityIdRestriction_Kind) Enum() *EntityIdRestriction_Kind {
	p := new(EntityIdRestriction_Kind)
	*p = x
	return p
}

func (x EntityIdRestriction_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityIdRestriction_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_enumTypes[1].Descriptor()
}

func (EntityIdRestriction_Kind) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_global_extensions_field_options_proto_enumTypes[1]
}

func (x EntityIdRestriction_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EntityIdRestriction_Kind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EntityIdRestriction_Kind(num)
	return nil
}

// Deprecated: Use EntityIdRestriction_Kind.Descriptor instead.
func (EntityIdRestriction_Kind) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescGZIP(), []int{7, 0}
}

type BGSFieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log               *LogOption `protobuf:"varint,1,opt,name=log,enum=bgs.protocol.LogOption" json:"log,omitempty"`
	ShardKey          *bool      `protobuf:"varint,2,opt,name=shard_key,json=shardKey" json:"shard_key,omitempty"`
	FanoutKey         *bool      `protobuf:"varint,3,opt,name=fanout_key,json=fanoutKey" json:"fanout_key,omitempty"`
	ClientInstanceKey *bool      `protobuf:"varint,4,opt,name=client_instance_key,json=clientInstanceKey" json:"client_instance_key,omitempty"`
	RealizedEnum      *string    `protobuf:"bytes,5,opt,name=realized_enum,json=realizedEnum" json:"realized_enum,omitempty"`
}

func (x *BGSFieldOptions) Reset() {
	*x = BGSFieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BGSFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BGSFieldOptions) ProtoMessage() {}

func (x *BGSFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BGSFieldOptions.ProtoReflect.Descriptor instead.
func (*BGSFieldOptions) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescGZIP(), []int{0}
}

func (x *BGSFieldOptions) GetLog() LogOption {
	if x != nil && x.Log != nil {
		return *x.Log
	}
	return LogOption_HIDDEN
}

func (x *BGSFieldOptions) GetShardKey() bool {
	if x != nil && x.ShardKey != nil {
		return *x.ShardKey
	}
	return false
}

func (x *BGSFieldOptions) GetFanoutKey() bool {
	if x != nil && x.FanoutKey != nil {
		return *x.FanoutKey
	}
	return false
}

func (x *BGSFieldOptions) GetClientInstanceKey() bool {
	if x != nil && x.ClientInstanceKey != nil {
		return *x.ClientInstanceKey
	}
	return false
}

func (x *BGSFieldOptions) GetRealizedEnum() string {
	if x != nil && x.RealizedEnum != nil {
		return *x.RealizedEnum
	}
	return ""
}

type FieldRestriction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signed   *SignedFieldRestriction   `protobuf:"bytes,1,opt,name=signed" json:"signed,omitempty"`
	Unsigned *UnsignedFieldRestriction `protobuf:"bytes,2,opt,name=unsigned" json:"unsigned,omitempty"`
	Float    *FloatFieldRestriction    `protobuf:"bytes,3,opt,name=float" json:"float,omitempty"`
	String_  *StringFieldRestriction   `protobuf:"bytes,4,opt,name=string" json:"string,omitempty"`
	Repeated *RepeatedFieldRestriction `protobuf:"bytes,5,opt,name=repeated" json:"repeated,omitempty"`
	Message  *MessageFieldRestriction  `protobuf:"bytes,6,opt,name=message" json:"message,omitempty"`
	EntityId *EntityIdRestriction      `protobuf:"bytes,7,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Bytes    *StringFieldRestriction   `protobuf:"bytes,8,opt,name=bytes" json:"bytes,omitempty"`
}

func (x *FieldRestriction) Reset() {
	*x = FieldRestriction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldRestriction) ProtoMessage() {}

func (x *FieldRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldRestriction.ProtoReflect.Descriptor instead.
func (*FieldRestriction) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescGZIP(), []int{1}
}

func (x *FieldRestriction) GetSigned() *SignedFieldRestriction {
	if x != nil {
		return x.Signed
	}
	return nil
}

func (x *FieldRestriction) GetUnsigned() *UnsignedFieldRestriction {
	if x != nil {
		return x.Unsigned
	}
	return nil
}

func (x *FieldRestriction) GetFloat() *FloatFieldRestriction {
	if x != nil {
		return x.Float
	}
	return nil
}

func (x *FieldRestriction) GetString_() *StringFieldRestriction {
	if x != nil {
		return x.String_
	}
	return nil
}

func (x *FieldRestriction) GetRepeated() *RepeatedFieldRestriction {
	if x != nil {
		return x.Repeated
	}
	return nil
}

func (x *FieldRestriction) GetMessage() *MessageFieldRestriction {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *FieldRestriction) GetEntityId() *EntityIdRestriction {
	if x != nil {
		return x.EntityId
	}
	return nil
}

func (x *FieldRestriction) GetBytes() *StringFieldRestriction {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type RepeatedFieldRestriction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size     *UnsignedIntRange         `protobuf:"bytes,1,opt,name=size" json:"size,omitempty"`
	Unique   *bool                     `protobuf:"varint,2,opt,name=unique" json:"unique,omitempty"`
	Signed   *SignedFieldRestriction   `protobuf:"bytes,3,opt,name=signed" json:"signed,omitempty"`
	Unsigned *UnsignedFieldRestriction `protobuf:"bytes,4,opt,name=unsigned" json:"unsigned,omitempty"`
	Float    *FloatFieldRestriction    `protobuf:"bytes,5,opt,name=float" json:"float,omitempty"`
	String_  *StringFieldRestriction   `protobuf:"bytes,6,opt,name=string" json:"string,omitempty"`
	EntityId *EntityIdRestriction      `protobuf:"bytes,7,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Bytes    *StringFieldRestriction   `protobuf:"bytes,8,opt,name=bytes" json:"bytes,omitempty"`
}

func (x *RepeatedFieldRestriction) Reset() {
	*x = RepeatedFieldRestriction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedFieldRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedFieldRestriction) ProtoMessage() {}

func (x *RepeatedFieldRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedFieldRestriction.ProtoReflect.Descriptor instead.
func (*RepeatedFieldRestriction) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescGZIP(), []int{2}
}

func (x *RepeatedFieldRestriction) GetSize() *UnsignedIntRange {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *RepeatedFieldRestriction) GetUnique() bool {
	if x != nil && x.Unique != nil {
		return *x.Unique
	}
	return false
}

func (x *RepeatedFieldRestriction) GetSigned() *SignedFieldRestriction {
	if x != nil {
		return x.Signed
	}
	return nil
}

func (x *RepeatedFieldRestriction) GetUnsigned() *UnsignedFieldRestriction {
	if x != nil {
		return x.Unsigned
	}
	return nil
}

func (x *RepeatedFieldRestriction) GetFloat() *FloatFieldRestriction {
	if x != nil {
		return x.Float
	}
	return nil
}

func (x *RepeatedFieldRestriction) GetString_() *StringFieldRestriction {
	if x != nil {
		return x.String_
	}
	return nil
}

func (x *RepeatedFieldRestriction) GetEntityId() *EntityIdRestriction {
	if x != nil {
		return x.EntityId
	}
	return nil
}

func (x *RepeatedFieldRestriction) GetBytes() *StringFieldRestriction {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type SignedFieldRestriction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limits  *SignedIntRange `protobuf:"bytes,1,opt,name=limits" json:"limits,omitempty"`
	Exclude []int64         `protobuf:"zigzag64,2,rep,name=exclude" json:"exclude,omitempty"`
}

func (x *SignedFieldRestriction) Reset() {
	*x = SignedFieldRestriction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedFieldRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedFieldRestriction) ProtoMessage() {}

func (x *SignedFieldRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedFieldRestriction.ProtoReflect.Descriptor instead.
func (*SignedFieldRestriction) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescGZIP(), []int{3}
}

func (x *SignedFieldRestriction) GetLimits() *SignedIntRange {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *SignedFieldRestriction) GetExclude() []int64 {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type UnsignedFieldRestriction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limits  *UnsignedIntRange `protobuf:"bytes,1,opt,name=limits" json:"limits,omitempty"`
	Exclude []uint64          `protobuf:"varint,2,rep,name=exclude" json:"exclude,omitempty"`
}

func (x *UnsignedFieldRestriction) Reset() {
	*x = UnsignedFieldRestriction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsignedFieldRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsignedFieldRestriction) ProtoMessage() {}

func (x *UnsignedFieldRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsignedFieldRestriction.ProtoReflect.Descriptor instead.
func (*UnsignedFieldRestriction) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescGZIP(), []int{4}
}

func (x *UnsignedFieldRestriction) GetLimits() *UnsignedIntRange {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *UnsignedFieldRestriction) GetExclude() []uint64 {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type FloatFieldRestriction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limits  *FloatRange `protobuf:"bytes,1,opt,name=limits" json:"limits,omitempty"`
	Exclude []float32   `protobuf:"fixed32,2,rep,name=exclude" json:"exclude,omitempty"`
}

func (x *FloatFieldRestriction) Reset() {
	*x = FloatFieldRestriction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatFieldRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatFieldRestriction) ProtoMessage() {}

func (x *FloatFieldRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatFieldRestriction.ProtoReflect.Descriptor instead.
func (*FloatFieldRestriction) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescGZIP(), []int{5}
}

func (x *FloatFieldRestriction) GetLimits() *FloatRange {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *FloatFieldRestriction) GetExclude() []float32 {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type StringFieldRestriction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size    *UnsignedIntRange `protobuf:"bytes,1,opt,name=size" json:"size,omitempty"`
	Exclude []string          `protobuf:"bytes,2,rep,name=exclude" json:"exclude,omitempty"`
}

func (x *StringFieldRestriction) Reset() {
	*x = StringFieldRestriction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringFieldRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringFieldRestriction) ProtoMessage() {}

func (x *StringFieldRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringFieldRestriction.ProtoReflect.Descriptor instead.
func (*StringFieldRestriction) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescGZIP(), []int{6}
}

func (x *StringFieldRestriction) GetSize() *UnsignedIntRange {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *StringFieldRestriction) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type EntityIdRestriction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Needed *bool                     `protobuf:"varint,1,opt,name=needed" json:"needed,omitempty"`
	Kind   *EntityIdRestriction_Kind `protobuf:"varint,2,opt,name=kind,enum=bgs.protocol.EntityIdRestriction_Kind" json:"kind,omitempty"`
}

func (x *EntityIdRestriction) Reset() {
	*x = EntityIdRestriction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityIdRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityIdRestriction) ProtoMessage() {}

func (x *EntityIdRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityIdRestriction.ProtoReflect.Descriptor instead.
func (*EntityIdRestriction) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescGZIP(), []int{7}
}

func (x *EntityIdRestriction) GetNeeded() bool {
	if x != nil && x.Needed != nil {
		return *x.Needed
	}
	return false
}

func (x *EntityIdRestriction) GetKind() EntityIdRestriction_Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return EntityIdRestriction_ANY
}

type MessageFieldRestriction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Needed *bool `protobuf:"varint,1,opt,name=needed" json:"needed,omitempty"`
}

func (x *MessageFieldRestriction) Reset() {
	*x = MessageFieldRestriction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageFieldRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFieldRestriction) ProtoMessage() {}

func (x *MessageFieldRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFieldRestriction.ProtoReflect.Descriptor instead.
func (*MessageFieldRestriction) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescGZIP(), []int{8}
}

func (x *MessageFieldRestriction) GetNeeded() bool {
	if x != nil && x.Needed != nil {
		return *x.Needed
	}
	return false
}

var File_bgs_low_pb_client_global_extensions_field_options_proto protoreflect.FileDescriptor

var file_bgs_low_pb_client_global_extensions_field_options_proto_rawDesc = []byte{
	0x0a, 0x37, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x67, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2f, 0x62, 0x67, 0x73, 0x2f, 0x6c,
	0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x67, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x0f, 0x42,
	0x47, 0x53, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29,
	0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x62, 0x67,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x61,
	0x72, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x61, 0x6e, 0x6f, 0x75, 0x74,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x61, 0x6e, 0x6f,
	0x75, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x64, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x8e, 0x04, 0x0a, 0x10, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x3c, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x12, 0x42, 0x0a,
	0x08, 0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x55,
	0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x12, 0x39, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x3c, 0x0a, 0x06,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x62,
	0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x42, 0x0a, 0x08, 0x72, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x62,
	0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x3f,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x3e, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x3a, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x22, 0xdd, 0x03, 0x0a, 0x18,
	0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x49, 0x6e,
	0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52,
	0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x12, 0x42, 0x0a, 0x08, 0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x75, 0x6e,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x12, 0x39, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52,
	0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12,
	0x3e, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x3a, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x22, 0x68, 0x0a, 0x16, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x12, 0x52, 0x07, 0x65, 0x78,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x22, 0x6c, 0x0a, 0x18, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x36, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x65, 0x78, 0x63, 0x6c,
	0x75, 0x64, 0x65, 0x22, 0x63, 0x0a, 0x15, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x06,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62,
	0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52,
	0x07, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x22, 0x66, 0x0a, 0x16, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65,
	0x22, 0xd0, 0x01, 0x0a, 0x13, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x65, 0x65, 0x64,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6e, 0x65, 0x65, 0x64, 0x65, 0x64,
	0x12, 0x3a, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26,
	0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x65, 0x0a, 0x04,
	0x4b, 0x69, 0x6e, 0x64, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4e, 0x59, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x41,
	0x4d, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17,
	0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4f, 0x52, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f,
	0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x52,
	0x56, 0x49, 0x43, 0x45, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45,
	0x4c, 0x10, 0x05, 0x22, 0x31, 0x0a, 0x17, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x65, 0x65, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x6e, 0x65, 0x65, 0x64, 0x65, 0x64, 0x2a, 0x20, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x49, 0x44, 0x44, 0x45, 0x4e, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x48, 0x45, 0x58, 0x10, 0x02, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6a, 0x62, 0x72, 0x69, 0x67, 0x61, 0x74, 0x6f,
	0x2f, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x78, 0x2f, 0x62, 0x6e, 0x65, 0x74, 0x2f, 0x62, 0x67,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
}

var (
	file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescOnce sync.Once
	file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescData = file_bgs_low_pb_client_global_extensions_field_options_proto_rawDesc
)

func file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescGZIP() []byte {
	file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescOnce.Do(func() {
		file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescData)
	})
	return file_bgs_low_pb_client_global_extensions_field_options_proto_rawDescData
}

var file_bgs_low_pb_client_global_extensions_field_options_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bgs_low_pb_client_global_extensions_field_options_proto_goTypes = []interface{}{
	(LogOption)(0),                   // 0: bgs.protocol.LogOption
	(EntityIdRestriction_Kind)(0),    // 1: bgs.protocol.EntityIdRestriction.Kind
	(*BGSFieldOptions)(nil),          // 2: bgs.protocol.BGSFieldOptions
	(*FieldRestriction)(nil),         // 3: bgs.protocol.FieldRestriction
	(*RepeatedFieldRestriction)(nil), // 4: bgs.protocol.RepeatedFieldRestriction
	(*SignedFieldRestriction)(nil),   // 5: bgs.protocol.SignedFieldRestriction
	(*UnsignedFieldRestriction)(nil), // 6: bgs.protocol.UnsignedFieldRestriction
	(*FloatFieldRestriction)(nil),    // 7: bgs.protocol.FloatFieldRestriction
	(*StringFieldRestriction)(nil),   // 8: bgs.protocol.StringFieldRestriction
	(*EntityIdRestriction)(nil),      // 9: bgs.protocol.EntityIdRestriction
	(*MessageFieldRestriction)(nil),  // 10: bgs.protocol.MessageFieldRestriction
	(*UnsignedIntRange)(nil),         // 11: bgs.protocol.UnsignedIntRange
	(*SignedIntRange)(nil),           // 12: bgs.protocol.SignedIntRange
	(*FloatRange)(nil),               // 13: bgs.protocol.FloatRange
}
var file_bgs_low_pb_client_global_extensions_field_options_proto_depIdxs = []int32{
	0,  // 0: bgs.protocol.BGSFieldOptions.log:type_name -> bgs.protocol.LogOption
	5,  // 1: bgs.protocol.FieldRestriction.signed:type_name -> bgs.protocol.SignedFieldRestriction
	6,  // 2: bgs.protocol.FieldRestriction.unsigned:type_name -> bgs.protocol.UnsignedFieldRestriction
	7,  // 3: bgs.protocol.FieldRestriction.float:type_name -> bgs.protocol.FloatFieldRestriction
	8,  // 4: bgs.protocol.FieldRestriction.string:type_name -> bgs.protocol.StringFieldRestriction
	4,  // 5: bgs.protocol.FieldRestriction.repeated:type_name -> bgs.protocol.RepeatedFieldRestriction
	10, // 6: bgs.protocol.FieldRestriction.message:type_name -> bgs.protocol.MessageFieldRestriction
	9,  // 7: bgs.protocol.FieldRestriction.entity_id:type_name -> bgs.protocol.EntityIdRestriction
	8,  // 8: bgs.protocol.FieldRestriction.bytes:type_name -> bgs.protocol.StringFieldRestriction
	11, // 9: bgs.protocol.RepeatedFieldRestriction.size:type_name -> bgs.protocol.UnsignedIntRange
	5,  // 10: bgs.protocol.RepeatedFieldRestriction.signed:type_name -> bgs.protocol.SignedFieldRestriction
	6,  // 11: bgs.protocol.RepeatedFieldRestriction.unsigned:type_name -> bgs.protocol.UnsignedFieldRestriction
	7,  // 12: bgs.protocol.RepeatedFieldRestriction.float:type_name -> bgs.protocol.FloatFieldRestriction
	8,  // 13: bgs.protocol.RepeatedFieldRestriction.string:type_name -> bgs.protocol.StringFieldRestriction
	9,  // 14: bgs.protocol.RepeatedFieldRestriction.entity_id:type_name -> bgs.protocol.EntityIdRestriction
	8,  // 15: bgs.protocol.RepeatedFieldRestriction.bytes:type_name -> bgs.protocol.StringFieldRestriction
	12, // 16: bgs.protocol.SignedFieldRestriction.limits:type_name -> bgs.protocol.SignedIntRange
	11, // 17: bgs.protocol.UnsignedFieldRestriction.limits:type_name -> bgs.protocol.UnsignedIntRange
	13, // 18: bgs.protocol.FloatFieldRestriction.limits:type_name -> bgs.protocol.FloatRange
	11, // 19: bgs.protocol.StringFieldRestriction.size:type_name -> bgs.protocol.UnsignedIntRange
	1,  // 20: bgs.protocol.EntityIdRestriction.kind:type_name -> bgs.protocol.EntityIdRestriction.Kind
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_bgs_low_pb_client_global_extensions_field_options_proto_init() }
func file_bgs_low_pb_client_global_extensions_field_options_proto_init() {
	if File_bgs_low_pb_client_global_extensions_field_options_proto != nil {
		return
	}
	file_bgs_low_pb_client_global_extensions_range_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BGSFieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldRestriction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedFieldRestriction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedFieldRestriction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsignedFieldRestriction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatFieldRestriction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringFieldRestriction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityIdRestriction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageFieldRestriction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bgs_low_pb_client_global_extensions_field_options_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bgs_low_pb_client_global_extensions_field_options_proto_goTypes,
		DependencyIndexes: file_bgs_low_pb_client_global_extensions_field_options_proto_depIdxs,
		EnumInfos:         file_bgs_low_pb_client_global_extensions_field_options_proto_enumTypes,
		MessageInfos:      file_bgs_low_pb_client_global_extensions_field_options_proto_msgTypes,
	}.Build()
	File_bgs_low_pb_client_global_extensions_field_options_proto = out.File
	file_bgs_low_pb_client_global_extensions_field_options_proto_rawDesc = nil
	file_bgs_low_pb_client_global_extensions_field_options_proto_goTypes = nil
	file_bgs_low_pb_client_global_extensions_field_options_proto_depIdxs = nil
}
