// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: bgs/low/pb/client/global_extensions/message_options.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BGSMessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomSelectShard *bool `protobuf:"varint,1,opt,name=custom_select_shard,json=customSelectShard" json:"custom_select_shard,omitempty"`
	CustomValidator   *bool `protobuf:"varint,2,opt,name=custom_validator,json=customValidator" json:"custom_validator,omitempty"`
}

func (x *BGSMessageOptions) Reset() {
	*x = BGSMessageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_global_extensions_message_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BGSMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BGSMessageOptions) ProtoMessage() {}

func (x *BGSMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_global_extensions_message_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BGSMessageOptions.ProtoReflect.Descriptor instead.
func (*BGSMessageOptions) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_message_options_proto_rawDescGZIP(), []int{0}
}

func (x *BGSMessageOptions) GetCustomSelectShard() bool {
	if x != nil && x.CustomSelectShard != nil {
		return *x.CustomSelectShard
	}
	return false
}

func (x *BGSMessageOptions) GetCustomValidator() bool {
	if x != nil && x.CustomValidator != nil {
		return *x.CustomValidator
	}
	return false
}

var File_bgs_low_pb_client_global_extensions_message_options_proto protoreflect.FileDescriptor

var file_bgs_low_pb_client_global_extensions_message_options_proto_rawDesc = []byte{
	0x0a, 0x39, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x67, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x11, 0x42,
	0x47, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x2e, 0x0a, 0x13, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x12, 0x29, 0x0a, 0x10, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x30, 0x5a, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6a, 0x62, 0x72, 0x69, 0x67,
	0x61, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x78, 0x2f, 0x62, 0x6e, 0x65, 0x74,
	0x2f, 0x62, 0x67, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
}

var (
	file_bgs_low_pb_client_global_extensions_message_options_proto_rawDescOnce sync.Once
	file_bgs_low_pb_client_global_extensions_message_options_proto_rawDescData = file_bgs_low_pb_client_global_extensions_message_options_proto_rawDesc
)

func file_bgs_low_pb_client_global_extensions_message_options_proto_rawDescGZIP() []byte {
	file_bgs_low_pb_client_global_extensions_message_options_proto_rawDescOnce.Do(func() {
		file_bgs_low_pb_client_global_extensions_message_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_bgs_low_pb_client_global_extensions_message_options_proto_rawDescData)
	})
	return file_bgs_low_pb_client_global_extensions_message_options_proto_rawDescData
}

var file_bgs_low_pb_client_global_extensions_message_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bgs_low_pb_client_global_extensions_message_options_proto_goTypes = []interface{}{
	(*BGSMessageOptions)(nil), // 0: bgs.protocol.BGSMessageOptions
}
var file_bgs_low_pb_client_global_extensions_message_options_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bgs_low_pb_client_global_extensions_message_options_proto_init() }
func file_bgs_low_pb_client_global_extensions_message_options_proto_init() {
	if File_bgs_low_pb_client_global_extensions_message_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bgs_low_pb_client_global_extensions_message_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BGSMessageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bgs_low_pb_client_global_extensions_message_options_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bgs_low_pb_client_global_extensions_message_options_proto_goTypes,
		DependencyIndexes: file_bgs_low_pb_client_global_extensions_message_options_proto_depIdxs,
		MessageInfos:      file_bgs_low_pb_client_global_extensions_message_options_proto_msgTypes,
	}.Build()
	File_bgs_low_pb_client_global_extensions_message_options_proto = out.File
	file_bgs_low_pb_client_global_extensions_message_options_proto_rawDesc = nil
	file_bgs_low_pb_client_global_extensions_message_options_proto_goTypes = nil
	file_bgs_low_pb_client_global_extensions_message_options_proto_depIdxs = nil
}
