// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: bgs/low/pb/client/global_extensions/register_method_types.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientRegisterMethodType int32

const (
	ClientRegisterMethodType_REGISTER_CLIENT_NONE                      ClientRegisterMethodType = 0
	ClientRegisterMethodType_REGISTER_CLIENT_REGISTERED                ClientRegisterMethodType = 1
	ClientRegisterMethodType_REGISTER_CLIENT_UNREGISTERED              ClientRegisterMethodType = 2
	ClientRegisterMethodType_REGISTER_CLIENT_UNREGISTERED_NOTIFICATION ClientRegisterMethodType = 3
)

// Enum value maps for ClientRegisterMethodType.
var (
	ClientRegisterMethodType_name = map[int32]string{
		0: "REGISTER_CLIENT_NONE",
		1: "REGISTER_CLIENT_REGISTERED",
		2: "REGISTER_CLIENT_UNREGISTERED",
		3: "REGISTER_CLIENT_UNREGISTERED_NOTIFICATION",
	}
	ClientRegisterMethodType_value = map[string]int32{
		"REGISTER_CLIENT_NONE":                      0,
		"REGISTER_CLIENT_REGISTERED":                1,
		"REGISTER_CLIENT_UNREGISTERED":              2,
		"REGISTER_CLIENT_UNREGISTERED_NOTIFICATION": 3,
	}
)

func (x ClientRegisterMethodType) Enum() *ClientRegisterMethodType {
	p := new(ClientRegisterMethodType)
	*p = x
	return p
}

func (x ClientRegisterMethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientRegisterMethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_bgs_low_pb_client_global_extensions_register_method_types_proto_enumTypes[0].Descriptor()
}

func (ClientRegisterMethodType) Type() protoreflect.EnumType {
	return &file_bgs_low_pb_client_global_extensions_register_method_types_proto_enumTypes[0]
}

func (x ClientRegisterMethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ClientRegisterMethodType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ClientRegisterMethodType(num)
	return nil
}

// Deprecated: Use ClientRegisterMethodType.Descriptor instead.
func (ClientRegisterMethodType) EnumDescriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_global_extensions_register_method_types_proto_rawDescGZIP(), []int{0}
}

var File_bgs_low_pb_client_global_extensions_register_method_types_proto protoreflect.FileDescriptor

var file_bgs_low_pb_client_global_extensions_register_method_types_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2a,
	0xa5, 0x01, 0x0a, 0x18, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14,
	0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54,
	0x45, 0x52, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54,
	0x45, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54,
	0x45, 0x52, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x52, 0x45, 0x47, 0x49,
	0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x10, 0x02, 0x12, 0x2d, 0x0a, 0x29, 0x52, 0x45, 0x47, 0x49,
	0x53, 0x54, 0x45, 0x52, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x52, 0x45,
	0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x43,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6a, 0x62, 0x72, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2f,
	0x6c, 0x6f, 0x67, 0x70, 0x72, 0x6f, 0x78, 0x2f, 0x62, 0x6e, 0x65, 0x74, 0x2f, 0x62, 0x67, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
}

var (
	file_bgs_low_pb_client_global_extensions_register_method_types_proto_rawDescOnce sync.Once
	file_bgs_low_pb_client_global_extensions_register_method_types_proto_rawDescData = file_bgs_low_pb_client_global_extensions_register_method_types_proto_rawDesc
)

func file_bgs_low_pb_client_global_extensions_register_method_types_proto_rawDescGZIP() []byte {
	file_bgs_low_pb_client_global_extensions_register_method_types_proto_rawDescOnce.Do(func() {
		file_bgs_low_pb_client_global_extensions_register_method_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_bgs_low_pb_client_global_extensions_register_method_types_proto_rawDescData)
	})
	return file_bgs_low_pb_client_global_extensions_register_method_types_proto_rawDescData
}

var file_bgs_low_pb_client_global_extensions_register_method_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bgs_low_pb_client_global_extensions_register_method_types_proto_goTypes = []interface{}{
	(ClientRegisterMethodType)(0), // 0: bgs.protocol.ClientRegisterMethodType
}
var file_bgs_low_pb_client_global_extensions_register_method_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bgs_low_pb_client_global_extensions_register_method_types_proto_init() }
func file_bgs_low_pb_client_global_extensions_register_method_types_proto_init() {
	if File_bgs_low_pb_client_global_extensions_register_method_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bgs_low_pb_client_global_extensions_register_method_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bgs_low_pb_client_global_extensions_register_method_types_proto_goTypes,
		DependencyIndexes: file_bgs_low_pb_client_global_extensions_register_method_types_proto_depIdxs,
		EnumInfos:         file_bgs_low_pb_client_global_extensions_register_method_types_proto_enumTypes,
	}.Build()
	File_bgs_low_pb_client_global_extensions_register_method_types_proto = out.File
	file_bgs_low_pb_client_global_extensions_register_method_types_proto_rawDesc = nil
	file_bgs_low_pb_client_global_extensions_register_method_types_proto_goTypes = nil
	file_bgs_low_pb_client_global_extensions_register_method_types_proto_depIdxs = nil
}
