// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package ws

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpContinuation-0]
	_ = x[OpText-1]
	_ = x[OpBinary-2]
	_ = x[OpClose-8]
	_ = x[OpPing-9]
	_ = x[OpPong-10]
}

const (
	_OpCode_name_0 = "OpContinuationOpTextOpBinary"
	_OpCode_name_1 = "OpCloseOpPingOpPong"
)

var (
	_OpCode_index_0 = [...]uint8{0, 14, 20, 28}
	_OpCode_index_1 = [...]uint8{0, 7, 13, 19}
)

func (i OpCode) String() string {
	switch {
	case i <= 2:
		return _OpCode_name_0[_OpCode_index_0[i]:_OpCode_index_0[i+1]]
	case 8 <= i && i <= 10:
		i -= 8
		return _OpCode_name_1[_OpCode_index_1[i]:_OpCode_index_1[i+1]]
	default:
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
