// Code generated by "stringer -type=PacketSource"; DO NOT EDIT.

package bgspacket

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SRC_CLIENT-0]
	_ = x[SRC_SERVER-1]
	_ = x[SRC_UNKNOWN-2]
}

const _PacketSource_name = "SRC_CLIENTSRC_SERVERSRC_UNKNOWN"

var _PacketSource_index = [...]uint8{0, 10, 20, 31}

func (i PacketSource) String() string {
	if i < 0 || i >= PacketSource(len(_PacketSource_index)-1) {
		return "PacketSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PacketSource_name[_PacketSource_index[i]:_PacketSource_index[i+1]]
}
